### ISSUE TITLE
cli PYTHONPATH=. python kebechet-cli --help failed with importError

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/kebechet#1091]
## Bug description
cli PYTHONPATH=. python kebechet-cli --help failed with ImportError

(kebechet) [shreekarSS@fedora kebechet]$ PYTHONPATH=. python kebechet-cli --help
Traceback (most recent call last):
  File "kebechet-cli", line 31, in <module>
    from kebechet.kebechet_runners import run, run_url, run_webhook, run_analysis
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/kebechet_runners.py", line 33, in <module>
    from kebechet.managers import (
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/__init__.py", line 6, in <module>
    from .version import VersionManager  # noqa F401
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/version/__init__.py", line 3, in <module>
    from .version import VersionManager  # noqa F401
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/version/version.py", line 31, in <module>
    from .release_triggers import (
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/version/release_triggers.py", line 27, in <module>
    from kebechet.managers import ManagerBase
ImportError: cannot import name 'ManagerBase' from partially initialized module 'kebechet.managers' (most likely due to a circular import) (/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/__init__.py)

### Steps to Reproduce
1.Follow this doc https://github.com/thoth-station/kebechet/blob/master/docs/getting-started.rst to install pre reqs 

### Actual behavior
cli failed with python ImportError

### Expected behavior
help cli should run without any issuess

**Comment by harshad16** [comment]
Does `pipenv run PYTHONPATH=.  ./kebechet-cli --help` also give same error?

**Comment by harshad16** [comment]
Seems like this issue is occured due this PR: https://github.com/thoth-station/kebechet/pull/1080/files
tested in local , gonna try to fix it or revert it.
