### ISSUE TITLE
package.version not found for kebechet itself?!

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#122]
**Describe the bug**
```

2018-07-28 08:03:18,279 [1] INFO     kebechet.utils: Cloning repository git@github.com:thoth-station/kebechet.git to /tmp/tmpjpnb5xrb
--
  | 2018-07-28 08:03:18,811 [1] INFO     kebechet.managers.update.update: Using Pipfile for dependency management
  | 2018-07-28 08:03:19,120 [1] DEBUG    kebechet.source_management: Issue 'No dependency management found' not found, not closing it
  | 2018-07-28 08:03:19,403 [1] DEBUG    kebechet.source_management: Issue 'Failed to perform initial lock of software stack' not found, not closing it
  | 2018-07-28 08:03:19,408 [1] ERROR    kebechet.config: An error occurred during run of manager {} <class 'kebechet.managers.update.update.UpdateManager'> for thoth-station/kebechet, skipping
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/site-packages/kebechet/config.py", line 168, in run
  | instance.run(**manager_configuration)
  | File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 595, in run
  | result = self._do_update(labels, pipenv_used=True)
  | File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 489, in _do_update
  | old_environment = self._get_all_packages_versions()
  | File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 148, in _get_all_packages_versions
  | 'version': package_info['version'][len('=='):]
  | KeyError: 'version'
  | 2018-07-28 08:03:19,409 [1] INFO     kebechet.config: Running manager 'info' for 'thoth-station/kebechet'
```

**Comment by goern** [comment]
is this still relevant?

**Comment by fridex** [comment]
I think so

**Comment by saisankargochhayat** [comment]
I think this happens when kebechet encounter's a block like -
```
        "igitt": {
            "git": "https://gitlab.com/gitmate/open-source/IGitt.git",
            "ref": "9f5faceb3b76ca44b2988f38371f4e3f4afd5672"
        },
```
Which doesn't have version key, so it fails with a key error at [line](https://github.com/thoth-station/kebechet/blob/b1df0a91423b3fa0f75376d214de4de13b8e7cb8/kebechet/managers/update/update.py#L147) 
Do we do something like create initial lock?
https://github.com/thoth-station/kebechet/blob/b1df0a91423b3fa0f75376d214de4de13b8e7cb8/kebechet/managers/update/update.py#L365

**Comment by fridex** [comment]
It would be more appreciate to create an issue stating that the application cannot be managed by kebechet as it uses a git version of a library/libraries.

**Comment by saisankargochhayat** [comment]
> It would be more appreciate to create an issue stating that the application cannot be managed by kebechet as it uses a git version of a library/libraries.

I will do that also stating the package which is causing the issue.
