### ISSUE TITLE
Use of non-standardized python package names causes issues

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#209]
```
2019-03-18 12:45:28,434 [1] ERROR    kebechet.config:171: An error occurred during run of manager {} <class 'kebechet.managers.update.update.UpdateManager'> for thoth-station/metrics-exporter, skipping
--
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/site-packages/kebechet/config.py", line 168, in run
  | instance.run(**manager_configuration)
  | File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 622, in run
  | result = self._do_update(labels, pipenv_used=True, req_dev=False)
  | File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 516, in _do_update
  | old_direct_dependencies_version = self._get_direct_dependencies_version()
  | File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 173, in _get_direct_dependencies_version
  | version = cls._get_dependency_version(dependency, is_dev=is_dev)
  | File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 99, in _get_dependency_version
  | f"Failed to retrieve version information for dependency {dependency}, (dev: {is_dev})")
  | kebechet.exception.InternalError: Failed to retrieve version information for dependency prometheus_client, (dev: False)


```

**Comment by fridex** [comment]
It looks like its due to non-standardized package name. Once we switch update manager to consume updates from thoth backend, this should vanish.

**Comment by goern** [comment]
I think this should have been closed by #11?

**Comment by fridex** [comment]
This still relevant.

**Comment by saisankargochhayat** [comment]
@fridex Currently we use fetch the version from the piplock, how do we consume updates from thoth-backend?

**Comment by fridex** [comment]
> @fridex Currently we use fetch the version from the piplock, how do we consume updates from thoth-backend?

kebechet will not use the current "update" manager - it will use manager "thoth_update" Kevin worked on - it will submit a request to thoth's api.

**Comment by saisankargochhayat** [comment]
Can we use the normalize function? Stated in the link you shared to check the file names in piplock? or would that be a bad idea?

**Comment by fridex** [comment]
> Can we use the normalize function? Stated in the link you shared to check the file names in piplock? or would that be a bad idea?

that's actually the right fix for this issue

**Comment by saisankargochhayat** [comment]
I will raise an PR :smiley:
