### ISSUE TITLE
Update manager throws RuntimeError if an issue already exists

### ISSUE THREAD

**Issue by CermakM** [thoth-station/kebechet#231]
**Describe the bug**
SSIA

**Expected behavior**
The issue is either updated or skipped and the Cron Job proceeds to the next one.

**Additional context**
<details><summary>OCP Logs</summary>
<pre>
<code>
2019-07-23 05:40:06,378 [1] INFO     root:128: Logging to a Sentry instance is turned off
2019-07-23 05:40:06,378 [1] INFO     root:150: Logging to rsyslog endpoint is turned off
2019-07-23 05:40:06,379 [1] DEBUG    kebechet:55: Debug mode turned on
2019-07-23 05:40:06,379 [1] DEBUG    kebechet:56: Kebechet version: '1.0.0'
2019-07-23 05:40:06,563 [1] DEBUG    kebechet.config:144: Using token 'b02*************************************'
2019-07-23 05:40:06,564 [1] INFO     kebechet.config:161: Running manager 'info' for 'CermakM/jupyter-datatables'
2019-07-23 05:40:06,899 [1] INFO     kebechet.managers.info.info:40: No issue to report to, exiting
2019-07-23 05:40:06,899 [1] INFO     kebechet.config:161: Running manager 'update' for 'CermakM/jupyter-datatables'
2019-07-23 05:40:06,901 [1] INFO     kebechet.utils:58: Cloning repository git@github.com:CermakM/jupyter-datatables.git to /tmp/tmpuy7ol982
2019-07-23 05:40:09,517 [1] INFO     kebechet.managers.update.update:620: Using Pipfile for dependency management
2019-07-23 05:40:09,858 [1] DEBUG    kebechet.source_management:101: Issue 'No dependency management found' not found, not closing it
2019-07-23 05:40:09,859 [1] INFO     kebechet.managers.update.update:368: Initial lock based on Pipfile will be done
2019-07-23 05:40:10,093 [1] DEBUG    kebechet.managers.manager:95: Running pipenv command 'pipenv lock'
2019-07-23 05:45:07,460 [1] WARNING  git.remote:734: Error lines received while fetching: error: failed to push some refs to 'git@github.com:CermakM/jupyter-datatables.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
2019-07-23 05:45:07,826 [1] ERROR    kebechet.config:171: An error occurred during run of manager {} <class 'kebechet.managers.update.update.UpdateManager'> for CermakM/jupyter-datatables, skipping
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kebechet/source_management.py", line 125, in _github_open_merge_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/CermakM/jupyter-datatables/pulls
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kebechet/config.py", line 168, in run
    instance.run(**manager_configuration)
  File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 622, in run
    result = self._do_update(labels, pipenv_used=True, req_dev=False)
  File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 493, in _do_update
    if self._create_initial_lock(labels, pipenv_used, req_dev):
  File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 388, in _create_initial_lock
    request = self.sm.open_merge_request(commit_msg, branch_name, body='', labels=labels)
  File "/usr/local/lib/python3.6/site-packages/kebechet/source_management.py", line 174, in open_merge_request
    merge_request = self._github_open_merge_request(commit_msg, body, branch_name)
  File "/usr/local/lib/python3.6/site-packages/kebechet/source_management.py", line 127, in _github_open_merge_request
    raise RuntimeError(f"Failed to create a pull request: {response.text}") from exc
RuntimeError: Failed to create a pull request: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for CermakM:kebechet-initial-lock."}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
2019-07-23 05:45:07,829 [1] INFO     kebechet.config:161: Running manager 'version' for 'CermakM/jupyter-datatables'
2019-07-23 05:45:08,109 [1] INFO     kebechet.config:174: Finished management for 'CermakM/jupyter-datatables'
2019-07-23 05:45:08,110 [1] DEBUG    kebechet.config:144: Using token 'b02*************************************'
2019-07-23 05:45:08,110 [1] INFO     kebechet.config:161: Running manager 'info' for 'CermakM/jupyter-require'
2019-07-23 05:45:08,361 [1] INFO     kebechet.managers.info.info:40: No issue to report to, exiting
2019-07-23 05:45:08,361 [1] INFO     kebechet.config:161: Running manager 'update' for 'CermakM/jupyter-require'
2019-07-23 05:45:08,361 [1] INFO     kebechet.utils:58: Cloning repository git@github.com:CermakM/jupyter-require.git to /tmp/tmpvqxkt5xg
2019-07-23 05:45:09,387 [1] INFO     kebechet.managers.update.update:620: Using Pipfile for dependency management
2019-07-23 05:45:09,607 [1] DEBUG    kebechet.source_management:101: Issue 'No dependency management found' not found, not closing it
2019-07-23 05:45:09,608 [1] INFO     kebechet.managers.update.update:368: Initial lock based on Pipfile will be done
2019-07-23 05:45:09,796 [1] DEBUG    kebechet.managers.manager:95: Running pipenv command 'pipenv lock'
2019-07-23 05:45:24,115 [1] WARNING  git.remote:734: Error lines received while fetching: error: failed to push some refs to 'git@github.com:CermakM/jupyter-require.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
2019-07-23 05:45:24,524 [1] ERROR    kebechet.config:171: An error occurred during run of manager {} <class 'kebechet.managers.update.update.UpdateManager'> for CermakM/jupyter-require, skipping
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kebechet/source_management.py", line 125, in _github_open_merge_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/CermakM/jupyter-require/pulls
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kebechet/config.py", line 168, in run
    instance.run(**manager_configuration)
  File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 622, in run
    result = self._do_update(labels, pipenv_used=True, req_dev=False)
  File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 493, in _do_update
    if self._create_initial_lock(labels, pipenv_used, req_dev):
  File "/usr/local/lib/python3.6/site-packages/kebechet/managers/update/update.py", line 388, in _create_initial_lock
    request = self.sm.open_merge_request(commit_msg, branch_name, body='', labels=labels)
  File "/usr/local/lib/python3.6/site-packages/kebechet/source_management.py", line 174, in open_merge_request
    merge_request = self._github_open_merge_request(commit_msg, body, branch_name)
  File "/usr/local/lib/python3.6/site-packages/kebechet/source_management.py", line 127, in _github_open_merge_request
    raise RuntimeError(f"Failed to create a pull request: {response.text}") from exc
RuntimeError: Failed to create a pull request: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for CermakM:kebechet-initial-lock."}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
2019-07-23 05:45:24,527 [1] INFO     kebechet.config:161: Running manager 'version' for 'CermakM/jupyter-require'
2019-07-23 05:45:24,743 [1] INFO     kebechet.config:174: Finished management for 'CermakM/jupyter-require'
</code>
</pre>
</details>

**Comment by CermakM** [comment]
Closing as an early-morning overlook ... the update manager actually behaves correctly since there are no more issues to raise, it is the **version** manager which should be running and it doesn't, for some reason, which confused me...
