### ISSUE TITLE
GitDB not found 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#322]
With `gitpython==1.0.1` in both requirement.txt and Pipfile.
Running it in cron job mode gives the following error - 
```
`Launching subshell in virtual environment…
 . /home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/bin/activate
[sai@sai-pc kebechet]$  . /home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/bin/activate
(kebechet) [sai@sai-pc kebechet]$ ./kebechet-cli run
Traceback (most recent call last):
  File "/home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.6/site-packages/git/__init__.py", line 22, in _init_externals
    import gitdb
ModuleNotFoundError: No module named 'gitdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./kebechet-cli", line 27, in <module>
    from kebechet.exception import WebhookPayloadError
  File "/home/sai/Downloads/thoth-station/kebechet/kebechet/__init__.py", line 4, in <module>
    from .managers import InfoManager
  File "/home/sai/Downloads/thoth-station/kebechet/kebechet/managers/__init__.py", line 3, in <module>
    from .info import InfoManager
  File "/home/sai/Downloads/thoth-station/kebechet/kebechet/managers/info/__init__.py", line 3, in <module>
    from .info import InfoManager
  File "/home/sai/Downloads/thoth-station/kebechet/kebechet/managers/info/info.py", line 23, in <module>
    from kebechet.managers.manager import ManagerBase
  File "/home/sai/Downloads/thoth-station/kebechet/kebechet/managers/manager.py", line 23, in <module>
    import git
  File "/home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.6/site-packages/git/__init__.py", line 30, in <module>
    _init_externals()
  File "/home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.6/site-packages/git/__init__.py", line 24, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH`
```
CC - @fridex

**Comment by saisankargochhayat** [comment]
So gitdb was removed as a dependency. 
https://github.com/gitpython-developers/GitPython/issues/983
