### ISSUE TITLE
PyYAML pkg updation causing, failure in other pkgs updates

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#335]
**Describe the bug**
kebechet instance updating user-api packages is failing as its unable to update the dependent package PyYAML.

**To Reproduce**
1. Run instance of kebechet on user-api
or 
go to logs of kebechet instance running aicoe-prod-bots.

**Expected behavior**
Update user-api package with a PR.

**Additional context**
Logs: 
```
Pipfile: /tmp/tmpkh7pgfo0/Pipfile
--
  | Using /home/user/.local/share/virtualenvs/user-5PivF_Od/bin/python (3.6.8) to create virtualenv…
  | created virtual environment CPython3.6.8.final.0-64 in 427ms
  | creator CPython3Posix(dest=/tmp/tmpkh7pgfo0/.venv, clear=False, global=False)
  | seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/tmp/tmp01txd1uc/seed-app-data/v1)
  | activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
  | Virtualenv location: /tmp/tmpkh7pgfo0/.venv
  | Locking [dev-packages] dependencies…
  | Locking [packages] dependencies…
  | FAIL
  | [pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
  | [pipenv.exceptions.ResolutionFailure]:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
  | [pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
  | [pipenv.exceptions.ResolutionFailure]:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
  | [pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
  | [pipenv.exceptions.ResolutionFailure]:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
  | [pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
  | [pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyyaml>=3.11,>=5.1,~=3.12
  | [pipenv.exceptions.ResolutionFailure]:       Tried: 3.10, 3.10, 3.11, 3.11, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1
  | [pipenv.exceptions.ResolutionFailure]:       Skipped pre-versions: 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 4.2b1, 4.2b2, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b7, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1
  | [pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  | First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
  | Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  | Hint: try $ pipenv lock --pre if it is a pre-release dependency.
  | ERROR: ERROR: Could not find a version that matches pyyaml>=3.11,>=5.1,~=3.12
  | Tried: 3.10, 3.10, 3.11, 3.11, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1
  | Skipped pre-versions: 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 4.2b1, 4.2b2, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b7, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1
  | There are incompatible versions in the resolved dependencies.
  | [pipenv.exceptions.ResolutionFailure]:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
  | [pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
  | [pipenv.exceptions.ResolutionFailure]:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
  | [pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
  | [pipenv.exceptions.ResolutionFailure]:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
  | [pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
  | [pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyyaml>=3.11,>=5.1,~=3.12
  | [pipenv.exceptions.ResolutionFailure]:       Tried: 3.10, 3.10, 3.11, 3.11, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1
  | [pipenv.exceptions.ResolutionFailure]:       Skipped pre-versions: 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 4.2b1, 4.2b2, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b7, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1
  | [pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  | First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
  | Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  | Hint: try $ pipenv lock --pre if it is a pre-release dependency.
  | ERROR: ERROR: Could not find a version that matches pyyaml>=3.11,>=5.1,~=3.12
  | Tried: 3.10, 3.10, 3.11, 3.11, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.12, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 3.13, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.1, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.1.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1, 5.3.1
  | Skipped pre-versions: 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13b1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 3.13rc1, 4.2b1, 4.2b2, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b5, 5.1b7, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.2b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1, 5.3b1
  | There are incompatible versions in the resolved dependencies.
  | ['Traceback (most recent call last):\n', '  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 501, in create_spinner\n    yield sp\n', '  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 649, in venv_resolve_deps\n    c = resolve(cmd, sp)\n', '  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/pipenv/utils.py", line 539, in resolve\n    sys.exit(c.return_code)\n', 'SystemExit: 1\n']
  | 2020-03-23 08:30:26,477   1 WARNING  kebechet.managers.update.update:532: Failed to update dependencies to their latest version, reporting issue

```

**Comment by saisankargochhayat** [comment]
The issue seems to arise from trying to satisfy the dependency of `thoth-common`, which seem to have `coala-bears==0.11.1` as a dev package, which requires -` pyyaml [required: ~=3.12, installed: 5.3]` which cannot seem to be satisfied.

**Comment by fridex** [comment]
> The issue seems to arise from trying to satisfy the dependency of `thoth-common`, which seem to have `coala-bears==0.11.1` as a dev package, which requires -` pyyaml [required: ~=3.12, installed: 5.3]` which cannot seem to be satisfied.
> Maybe remove `coala-bear` as a dependency in thoth-common dev if we aren't using it?

Coala should be present in the container image used for testing the code base with coala. Coala is not a dependency of any of the libraries/components in thoth - coala is not required to run the library or its test suite. Can it be removed from requirement files?

**Comment by saisankargochhayat** [comment]
> > The issue seems to arise from trying to satisfy the dependency of `thoth-common`, which seem to have `coala-bears==0.11.1` as a dev package, which requires -` pyyaml [required: ~=3.12, installed: 5.3]` which cannot seem to be satisfied.
> > Maybe remove `coala-bear` as a dependency in thoth-common dev if we aren't using it?
> 
> Coala should be present in the container image used for testing the code base with coala. Coala is not a dependency of any of the libraries/components in thoth - coala is not required to run the library or its test suite. Can it be removed from requirement files?

Should I make a PR removing `coala-bear` from thoth-common?

**Comment by fridex** [comment]
> Should I make a PR removing `coala-bear` from thoth-common?

Yes, free to do so. Also in other repos if you spot it. :+1:

**Comment by harshad16** [comment]
Thanks for the coala bear update. Awesome work like always.
The pyyaml issue also occurred in user-api and management-api update.
The issue was between mismatch of pyyaml version requirement.
connexion require pyyaml >5.1
kubernetes 10.1.0 requires pyyaml ~=3.1
which causes issue, the fixes was added in by making kubernetes stay at 10.0.0.
As 11.0.0 doesn't support argo-workflow and 10.1.0 cant be used due to pyyaml.

just for future references.
