### ISSUE TITLE
Kebechet fails to parse configuration file

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#446]
**Describe the bug**
Kebechet fails to parse configuration file

**To Reproduce**

**Expected behavior**
Kebechet not failing.

**Screenshots**
inputs
```
Name:                kebechet-job-08780a73
Namespace:           thoth-prod-tensorflow
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Thu Jun 18 09:14:53 +0200 (10 minutes ago)
Started:             Thu Jun 18 09:14:53 +0200 (10 minutes ago)
Finished:            Thu Jun 18 09:15:03 +0200 (10 minutes ago)
Duration:            10 seconds
Parameters:          
  WEBHOOK_PAYLOAD:   {"event": "push", "payload": {"ref": "refs/heads/master", "before": "feec8b824320eb188f5d65454e3f5e49be6bc056", "after": "e865be4a507239314ae0f433280946727d11727e", "repository": {"id": 248024741, "node_id": "MDEwOlJlcG9zaXRvcnkyNDgwMjQ3NDE=", "name": "aicoe-ci", "full_name": "thoth-station/aicoe-ci", "private": false, "owner": {"name": "thoth-station", "email": null, "login": "thoth-station", "id": 36954363, "node_id": "MDEyOk9yZ2FuaXphdGlvbjM2OTU0MzYz", "avatar_url": "https://avatars0.githubusercontent.com/u/36954363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/thoth-station", "html_url": "https://github.com/thoth-station", "followers_url": "https://api.github.com/users/thoth-station/followers", "following_url": "https://api.github.com/users/thoth-station/following{/other_user}", "gists_url": "https://api.github.com/users/thoth-station/gists{/gist_id}", "starred_url": "https://api.github.com/users/thoth-station/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/thoth-station/subscriptions", "organizations_url": "https://api.github.com/users/thoth-station/orgs", "repos_url": "https://api.github.com/users/thoth-station/repos", "events_url": "https://api.github.com/users/thoth-station/events{/privacy}", "received_events_url": "https://api.github.com/users/thoth-station/received_events", "type": "Organization", "site_admin": false}, "html_url": "https://github.com/thoth-station/aicoe-ci", "description": "Thoth-CI using TektonCD pipelines and triggers", "fork": false, "url": "https://github.com/thoth-station/aicoe-ci", "forks_url": "https://api.github.com/repos/thoth-station/aicoe-ci/forks", "keys_url": "https://api.github.com/repos/thoth-station/aicoe-ci/keys{/key_id}", "collaborators_url": "https://api.github.com/repos/thoth-station/aicoe-ci/collaborators{/collaborator}", "teams_url": "https://api.github.com/repos/thoth-station/aicoe-ci/teams", "hooks_url": "https://api.github.com/repos/thoth-station/aicoe-ci/hooks", "issue_events_url": "https://api.github.com/repos/thoth-station/aicoe-ci/issues/events{/number}", "events_url": "https://api.github.com/repos/thoth-station/aicoe-ci/events", "assignees_url": "https://api.github.com/repos/thoth-station/aicoe-ci/assignees{/user}", "branches_url": "https://api.github.com/repos/thoth-station/aicoe-ci/branches{/branch}", "tags_url": "https://api.github.com/repos/thoth-station/aicoe-ci/tags", "blobs_url": "https://api.github.com/repos/thoth-station/aicoe-ci/git/blobs{/sha}", "git_tags_url": "https://api.github.com/repos/thoth-station/aicoe-ci/git/tags{/sha}", "git_refs_url": "https://api.github.com/repos/thoth-station/aicoe-ci/git/refs{/sha}", "trees_url": "https://api.github.com/repos/thoth-station/aicoe-ci/git/trees{/sha}", "statuses_url": "https://api.github.com/repos/thoth-station/aicoe-ci/statuses/{sha}", "languages_url": "https://api.github.com/repos/thoth-station/aicoe-ci/languages", "stargazers_url": "https://api.github.com/repos/thoth-station/aicoe-ci/stargazers", "contributors_url": "https://api.github.com/repos/thoth-station/aicoe-ci/contributors", "subscribers_url": "https://api.github.com/repos/thoth-station/aicoe-ci/subscribers", "subscription_url": "https://api.github.com/repos/thoth-station/aicoe-ci/subscription", "commits_url": "https://api.github.com/repos/thoth-station/aicoe-ci/commits{/sha}", "git_commits_url": "https://api.github.com/repos/thoth-station/aicoe-ci/git/commits{/sha}", "comments_url": "https://api.github.com/repos/thoth-station/aicoe-ci/comments{/number}", "issue_comment_url": "https://api.github.com/repos/thoth-station/aicoe-ci/issues/comments{/number}", "contents_url": "https://api.github.com/repos/thoth-station/aicoe-ci/contents/{+path}", "compare_url": "https://api.github.com/repos/thoth-station/aicoe-ci/compare/{base}...{head}", "merges_url": "https://api.github.com/repos/thoth-station/aicoe-ci/merges", "archive_url": "https://api.github.com/repos/thoth-station/aicoe-ci/{archive_format}{/ref}", "downloads_url": "https://api.github.com/repos/thoth-station/aicoe-ci/downloads", "issues_url": "https://api.github.com/repos/thoth-station/aicoe-ci/issues{/number}", "pulls_url": "https://api.github.com/repos/thoth-station/aicoe-ci/pulls{/number}", "milestones_url": "https://api.github.com/repos/thoth-station/aicoe-ci/milestones{/number}", "notifications_url": "https://api.github.com/repos/thoth-station/aicoe-ci/notifications{?since,all,participating}", "labels_url": "https://api.github.com/repos/thoth-station/aicoe-ci/labels{/name}", "releases_url": "https://api.github.com/repos/thoth-station/aicoe-ci/releases{/id}", "deployments_url": "https://api.github.com/repos/thoth-station/aicoe-ci/deployments", "created_at": 1584464040, "updated_at": "2020-06-18T07:11:47Z", "pushed_at": 1592464492, "git_url": "git://github.com/thoth-station/aicoe-ci.git", "ssh_url": "git@github.com:thoth-station/aicoe-ci.git", "clone_url": "https://github.com/thoth-station/aicoe-ci.git", "svn_url": "https://github.com/thoth-station/aicoe-ci", "homepage": "", "size": 234, "stargazers_count": 2, "watchers_count": 2, "language": "Shell", "has_issues": true, "has_projects": false, "has_downloads": true, "has_wiki": false, "has_pages": false, "forks_count": 4, "mirror_url": null, "archived": false, "disabled": false, "open_issues_count": 4, "license": null, "forks": 4, "open_issues": 4, "watchers": 2, "default_branch": "master", "stargazers": 2, "master_branch": "master", "organization": "thoth-station"}, "pusher": {"name": "goern", "email": "goern@redhat.com"}, "organization": {"login": "thoth-station", "id": 36954363, "node_id": "MDEyOk9yZ2FuaXphdGlvbjM2OTU0MzYz", "url": "https://api.github.com/orgs/thoth-station", "repos_url": "https://api.github.com/orgs/thoth-station/repos", "events_url": "https://api.github.com/orgs/thoth-station/events", "hooks_url": "https://api.github.com/orgs/thoth-station/hooks", "issues_url": "https://api.github.com/orgs/thoth-station/issues", "members_url": "https://api.github.com/orgs/thoth-station/members{/member}", "public_members_url": "https://api.github.com/orgs/thoth-station/public_members{/member}", "avatar_url": "https://avatars0.githubusercontent.com/u/36954363?v=4", "description": "Using Artificial Intelligence to analyse and recommend Software Stacks for Artificial Intelligence applications."}, "sender": {"login": "goern", "id": 260331, "node_id": "MDQ6VXNlcjI2MDMzMQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/260331?v=4", "gravatar_id": "", "url": "https://api.github.com/users/goern", "html_url": "https://github.com/goern", "followers_url": "https://api.github.com/users/goern/followers", "following_url": "https://api.github.com/users/goern/following{/other_user}", "gists_url": "https://api.github.com/users/goern/gists{/gist_id}", "starred_url": "https://api.github.com/users/goern/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/goern/subscriptions", "organizations_url": "https://api.github.com/users/goern/orgs", "repos_url": "https://api.github.com/users/goern/repos", "events_url": "https://api.github.com/users/goern/events{/privacy}", "received_events_url": "https://api.github.com/users/goern/received_events", "type": "User", "site_admin": false}, "installation": {"id": 9515113, "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uOTUxNTExMw=="}, "created": false, "deleted": false, "forced": false, "base_ref": null, "compare": "https://github.com/thoth-station/aicoe-ci/compare/feec8b824320...e865be4a5072", "commits": [{"id": "2baeaadf0e94606773d2e1352400476b114b959d", "tree_id": "9bd70a9bcdfcdb007abc2de4307c02fddbef80d9", "distinct": true, "message": ":sparkles: no pipeline will no longer merge any PR", "timestamp": "2020-06-18T08:50:52+02:00", "url": "https://github.com/thoth-station/aicoe-ci/commit/2baeaadf0e94606773d2e1352400476b114b959d", "author": {"name": "Christoph G\u00f6rn", "email": "goern@redhat.com", "username": "goern"}, "committer": {"name": "Christoph G\u00f6rn", "email": "goern@redhat.com", "username": "goern"}, "added": [], "removed": [], "modified": ["pipeline/pipeline.yaml", "tasks/init-task.yaml", "trigger/git-pr-binding.yaml", "trigger/git-pr-template.yaml"]}, {"id": "68afa5f9ddf1eb36165bd5d97a67c59fd6d3662f", "tree_id": "6116f261d8ea0ec547a17906a05e5aa47eefccb4", "distinct": true, "message": "Merge branch 'master' into feature/no-more-merge", "timestamp": "2020-06-18T09:14:06+02:00", "url": "https://github.com/thoth-station/aicoe-ci/commit/68afa5f9ddf1eb36165bd5d97a67c59fd6d3662f", "author": {"name": "Christoph G\u00f6rn", "email": "goern@redhat.com", "username": "goern"}, "committer": {"name": "GitHub", "email": "noreply@github.com", "username": "web-flow"}, "added": ["OWNERS"], "removed": [], "modified": ["tasks/init-task.yaml"]}, {"id": "e865be4a507239314ae0f433280946727d11727e", "tree_id": "6116f261d8ea0ec547a17906a05e5aa47eefccb4", "distinct": true, "message": "Merge pull request #34 from goern/feature/no-more-merge\n\nno pipeline will no longer merge any PR", "timestamp": "2020-06-18T09:14:51+02:00", "url": "https://github.com/thoth-station/aicoe-ci/commit/e865be4a507239314ae0f433280946727d11727e", "author": {"name": "Christoph G\u00f6rn", "email": "goern@redhat.com", "username": "goern"}, "committer": {"name": "GitHub", "email": "noreply@github.com", "username": "web-flow"}, "added": [], "removed": [], "modified": ["pipeline/pipeline.yaml", "tasks/init-task.yaml", "trigger/git-pr-binding.yaml", "trigger/git-pr-template.yaml"]}], "head_commit": {"id": "e865be4a507239314ae0f433280946727d11727e", "tree_id": "6116f261d8ea0ec547a17906a05e5aa47eefccb4", "distinct": true, "message": "Merge pull request #34 from goern/feature/no-more-merge\n\nno pipeline will no longer merge any PR", "timestamp": "2020-06-18T09:14:51+02:00", "url": "https://github.com/thoth-station/aicoe-ci/commit/e865be4a507239314ae0f433280946727d11727e", "author": {"name": "Christoph G\u00f6rn", "email": "goern@redhat.com", "username": "goern"}, "committer": {"name": "GitHub", "email": "noreply@github.com", "username": "web-flow"}, "added": [], "removed": [], "modified": ["pipeline/pipeline.yaml", "tasks/init-task.yaml", "trigger/git-pr-binding.yaml", "trigger/git-pr-template.yaml"]}}, "service": "github"}
  IMAGE_STREAM_REGISTRY: docker-registry.default.svc:5000
  IMAGE_STREAM_NAMESPACE: thoth-infra-stage
  IMAGE_STREAM_TAG:  latest

STEP                       TEMPLATE                   PODNAME                           DURATION  MESSAGE
 ✖ kebechet-job-08780a73   kebechet-job                                                                                    
 └-✖ kebechet-webhook-run  kebechet-job/kebechet-job  kebechet-job-08780a73-1731103174  8s        failed with exit code 1  
```

logs
```
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 99, "funcname": "setup_integrations", "created": 1592464499.2906003, "asctime": "2020-06-18 07:14:59,290", "msecs": 290.6002998352051, "relative_created": 1191.2658214569092, "process": 1, "message": "Setting up integrations (with default = True)"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.2949615, "asctime": "2020-06-18 07:14:59,294", "msecs": 294.96145248413086, "relative_created": 1195.626974105835, "process": 1, "message": "Setting up previously not enabled integration logging"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.2956336, "asctime": "2020-06-18 07:14:59,295", "msecs": 295.63355445861816, "relative_created": 1196.2990760803223, "process": 1, "message": "Setting up previously not enabled integration stdlib"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.295786, "asctime": "2020-06-18 07:14:59,295", "msecs": 295.78590393066406, "relative_created": 1196.4514255523682, "process": 1, "message": "Setting up previously not enabled integration excepthook"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.2959378, "asctime": "2020-06-18 07:14:59,295", "msecs": 295.93777656555176, "relative_created": 1196.6032981872559, "process": 1, "message": "Setting up previously not enabled integration dedupe"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.296082, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.0820198059082, "relative_created": 1196.7475414276123, "process": 1, "message": "Setting up previously not enabled integration atexit"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.296164, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.16403579711914, "relative_created": 1196.8295574188232, "process": 1, "message": "Setting up previously not enabled integration modules"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.2963138, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.3137626647949, "relative_created": 1196.979284286499, "process": 1, "message": "Setting up previously not enabled integration argv"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592464499.2963855, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.3855266571045, "relative_created": 1197.0510482788086, "process": 1, "message": "Setting up previously not enabled integration threading"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2964504, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.4503765106201, "relative_created": 1197.1158981323242, "process": 1, "message": "Enabling integration logging"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2965055, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.5054512023926, "relative_created": 1197.1709728240967, "process": 1, "message": "Enabling integration stdlib"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2965574, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.5574264526367, "relative_created": 1197.2229480743408, "process": 1, "message": "Enabling integration excepthook"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2966084, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.60844802856445, "relative_created": 1197.2739696502686, "process": 1, "message": "Enabling integration dedupe"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2966835, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.68354988098145, "relative_created": 1197.3490715026855, "process": 1, "message": "Enabling integration atexit"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2968307, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.8306541442871, "relative_created": 1197.4961757659912, "process": 1, "message": "Enabling integration modules"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2969725, "asctime": "2020-06-18 07:14:59,296", "msecs": 296.97251319885254, "relative_created": 1197.6380348205566, "process": 1, "message": "Enabling integration argv"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592464499.2970874, "asctime": "2020-06-18 07:14:59,297", "msecs": 297.0874309539795, "relative_created": 1197.7529525756836, "process": 1, "message": "Enabling integration threading"}
kebechet-job-08780a73-1731103174: {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 329, "funcname": "init_logging", "created": 1592464499.297204, "asctime": "2020-06-18 07:14:59,297", "msecs": 297.20401763916016, "relative_created": 1197.8695392608643, "process": 1, "message": "No Sentry environment configured: it is recommended to provide Sentry environment to split reported exceptions based on different deployments when running in a cluster"}
kebechet-job-08780a73-1731103174: {"name": "kebechet", "levelname": "DEBUG", "module": "kebechet-cli", "lineno": 71, "funcname": "cli", "created": 1592464499.2979903, "asctime": "2020-06-18 07:14:59,297", "msecs": 297.9903221130371, "relative_created": 1198.6558437347412, "process": 1, "message": "Debug mode turned on"}
kebechet-job-08780a73-1731103174: {"name": "kebechet.services", "levelname": "INFO", "module": "services", "lineno": 65, "funcname": "__init__", "created": 1592464499.298745, "asctime": "2020-06-18 07:14:59,298", "msecs": 298.74491691589355, "relative_created": 1199.4104385375977, "process": 1, "message": "github service detected"}
kebechet-job-08780a73-1731103174: {"name": "kebechet.services", "levelname": "INFO", "module": "services", "lineno": 96, "funcname": "download_kebechet_config", "created": 1592464499.2989328, "asctime": "2020-06-18 07:14:59,298", "msecs": 298.9327907562256, "relative_created": 1199.5983123779297, "process": 1, "message": "Downloading from https://raw.githubusercontent.com/thoth-station/aicoe-ci/master/.thoth.yaml"}
kebechet-job-08780a73-1731103174: {"name": "kebechet.services", "levelname": "INFO", "module": "services", "lineno": 101, "funcname": "download_kebechet_config", "created": 1592464499.508457, "asctime": "2020-06-18 07:14:59,508", "msecs": 508.4569454193115, "relative_created": 1409.1224670410156, "process": 1, "message": "b'404: Not Found'"}
kebechet-job-08780a73-1731103174: {"name": "kebechet.config", "levelname": "DEBUG", "module": "config", "lineno": 97, "funcname": "run_url", "created": 1592464499.5087736, "asctime": "2020-06-18 07:14:59,508", "msecs": 508.7735652923584, "relative_created": 1409.4390869140625, "process": 1, "message": "Filename = /tmp/tmp1wif33a_"}
kebechet-job-08780a73-1731103174: {"name": "kebechet.services", "levelname": "INFO", "module": "services", "lineno": 65, "funcname": "__init__", "created": 1592464499.5089512, "asctime": "2020-06-18 07:14:59,508", "msecs": 508.95118713378906, "relative_created": 1409.6167087554932, "process": 1, "message": "github service detected"}
kebechet-job-08780a73-1731103174: {"name": "kebechet.services", "levelname": "INFO", "module": "services", "lineno": 96, "funcname": "download_kebechet_config", "created": 1592464499.50907, "asctime": "2020-06-18 07:14:59,509", "msecs": 509.06991958618164, "relative_created": 1409.7354412078857, "process": 1, "message": "Downloading from https://raw.githubusercontent.com/thoth-station/aicoe-ci/master/.thoth.yaml"}
kebechet-job-08780a73-1731103174: {"name": "kebechet.services", "levelname": "INFO", "module": "services", "lineno": 101, "funcname": "download_kebechet_config", "created": 1592464499.614901, "asctime": "2020-06-18 07:14:59,614", "msecs": 614.901065826416, "relative_created": 1515.5665874481201, "process": 1, "message": "b'404: Not Found'"}
kebechet-job-08780a73-1731103174: Traceback (most recent call last):
kebechet-job-08780a73-1731103174:   File "/home/user/kebechet/config.py", line 63, in _managers_from_file
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 223, "funcname": "_send_event", "created": 1592464499.6333973, "asctime": "2020-06-18 07:14:59,633", "msecs": 633.3973407745361, "relative_created": 1534.0628623962402, "process": 1, "message": "Sending event, type:null level:error event_id:f6113b2ba7e6462bbfdf25b9e05b3e4f project:1298083 host:sentry.io"}
kebechet-job-08780a73-1731103174:     return yaml.safe_load(content).pop("managers") or []
kebechet-job-08780a73-1731103174: KeyError: 'managers'
kebechet-job-08780a73-1731103174: The above exception was the direct cause of the following exception:
kebechet-job-08780a73-1731103174: Traceback (most recent call last):
kebechet-job-08780a73-1731103174:   File "kebechet-cli", line 115, in <module>
kebechet-job-08780a73-1731103174:     cli()
kebechet-job-08780a73-1731103174:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/click/core.py", line 829, in __call__
kebechet-job-08780a73-1731103174:     return self.main(*args, **kwargs)
kebechet-job-08780a73-1731103174:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/click/core.py", line 782, in main
kebechet-job-08780a73-1731103174:     rv = self.invoke(ctx)
kebechet-job-08780a73-1731103174:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
kebechet-job-08780a73-1731103174:     return _process_result(sub_ctx.command.invoke(sub_ctx))
kebechet-job-08780a73-1731103174:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
kebechet-job-08780a73-1731103174:     return ctx.invoke(self.callback, **ctx.params)
kebechet-job-08780a73-1731103174:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/click/core.py", line 610, in invoke
kebechet-job-08780a73-1731103174:     return callback(*args, **kwargs)
kebechet-job-08780a73-1731103174:   File "kebechet-cli", line 111, in cli_run_webhook
kebechet-job-08780a73-1731103174:     config.run_webhook(payload=payload)
kebechet-job-08780a73-1731103174:   File "/home/user/kebechet/config.py", line 92, in run_webhook
kebechet-job-08780a73-1731103174:     cls.run_url(parsed_payload['url'], parsed_payload['service_type'], parsed_payload, True)
kebechet-job-08780a73-1731103174:   File "/home/user/kebechet/config.py", line 103, in run_url
kebechet-job-08780a73-1731103174:     managers = cls._managers_from_file(tempfile.name)
kebechet-job-08780a73-1731103174:   File "/home/user/kebechet/config.py", line 67, in _managers_from_file
kebechet-job-08780a73-1731103174:     ) from exc
kebechet-job-08780a73-1731103174: kebechet.exception.ConfigurationError: Failed to parse configuration file: {str(exc)}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "atexit", "lineno": 51, "funcname": "_shutdown", "created": 1592464499.6360822, "asctime": "2020-06-18 07:14:59,636", "msecs": 636.0821723937988, "relative_created": 1536.747694015503, "process": 1, "message": "atexit: got shutdown signal"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "atexit", "lineno": 55, "funcname": "_shutdown", "created": 1592464499.6362867, "asctime": "2020-06-18 07:14:59,636", "msecs": 636.286735534668, "relative_created": 1536.952257156372, "process": 1, "message": "atexit: shutting down client"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 331, "funcname": "flush", "created": 1592464499.6363761, "asctime": "2020-06-18 07:14:59,636", "msecs": 636.376142501831, "relative_created": 1537.0416641235352, "process": 1, "message": "Flushing HTTP transport"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 105, "funcname": "flush", "created": 1592464499.6364398, "asctime": "2020-06-18 07:14:59,636", "msecs": 636.4398002624512, "relative_created": 1537.1053218841553, "process": 1, "message": "background worker got flush request"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 116, "funcname": "_wait_flush", "created": 1592464499.7367537, "asctime": "2020-06-18 07:14:59,736", "msecs": 736.7537021636963, "relative_created": 1637.4192237854004, "process": 1, "message": "0 event(s) pending on flush"}
kebechet-job-08780a73-1731103174: Sentry is attempting to send 0 pending error messages
kebechet-job-08780a73-1731103174: Waiting up to 2 seconds
kebechet-job-08780a73-1731103174: Press Ctrl-C to quit
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 109, "funcname": "flush", "created": 1592464499.8094723, "asctime": "2020-06-18 07:14:59,809", "msecs": 809.4723224639893, "relative_created": 1710.1378440856934, "process": 1, "message": "background worker flushed"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 337, "funcname": "kill", "created": 1592464499.8097394, "asctime": "2020-06-18 07:14:59,809", "msecs": 809.739351272583, "relative_created": 1710.404872894287, "process": 1, "message": "Killing HTTP transport"}
kebechet-job-08780a73-1731103174: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 92, "funcname": "kill", "created": 1592464499.809854, "asctime": "2020-06-18 07:14:59,809", "msecs": 809.8540306091309, "relative_created": 1710.519552230835, "process": 1, "message": "background worker got kill request"}
```

**Additional Context**
There are many failed Kebechet workflows.

**Comment by fridex** [comment]
We should probably create an issue if the required parts of the config file are missing. Maybe validate the config file against schema.

**Comment by saisankargochhayat** [comment]
Should I close this issue?

**Comment by fridex** [comment]
Yes, the fix was already merged :+1:
