### ISSUE TITLE
pre-commit checks are failing

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#466]
```

[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://gitlab.com/PyCQA/flake8.
[INFO] Initializing environment for https://gitlab.com/PyCQA/flake8:pep8-naming.
[INFO] Initializing environment for https://github.com/mgedmin/check-manifest.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/mgedmin/check-manifest.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing kebechet/managers/thoth_advise/README.rst
Fixing app.sh
Fixing kebechet/managers/thoth_provenance/README.rst
Fixing openshift/kebechet-template.yaml
Fixing playbooks/roles/thoth-kebechet-bot/tasks/main.yaml
Fixing .github/workflows/codeql.yml
Fixing config/thoth.yaml
Fixing playbooks/roles/thoth-kebechet-imagestreams/tasks/main.yaml
Fixing playbooks/provision.yaml
Fixing playbooks/deprovision.yaml
Fixing Dockerfile
Fixing .thoth.yaml

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing kebechet/managers/thoth_advise/README.rst
Fixing kebechet/managers/README.rst
Fixing kebechet/managers/thoth_provenance/README.rst
Fixing openshift/kebechet-template.yaml
Fixing kebechet/managers/update/README.rst
Fixing requirements.txt
Fixing kebechet/managers/info/README.rst
Fixing workflows/templates/kebechet-job.yaml

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
Check for byte-order marker..............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks................................................Passed
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Failed
- hook id: pydocstyle
- exit code: 1

setup.py:1 at module level:
        D100: Missing docstring in public module
setup.py:6 in public function `get_install_requires`:
        D103: Missing docstring in public function
setup.py:13 in public function `get_version`:
        D103: Missing docstring in public function

Check Toml...............................................................Passed
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

Traceback (most recent call last):
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/bin/check-yaml", line 8, in <module>
    sys.exit(main())
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/check_yaml.py", line 63, in main
    load_fn(f)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 723, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 440, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 257, in construct_mapping
    if self.check_mapping_key(node, key_node, mapping, key, value):
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "openshift/cronJob-template.yaml", line 22, column 7
found duplicate key "annotations" with value "{}" (original value: "{}")
  in "openshift/cronJob-template.yaml", line 27, column 7

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

Traceback (most recent call last):
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/bin/check-yaml", line 8, in <module>
    sys.exit(main())
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/check_yaml.py", line 63, in main
    load_fn(f)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 723, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 440, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 257, in construct_mapping
    if self.check_mapping_key(node, key_node, mapping, key, value):
  File "/tekton/home/.cache/pre-commit/repokcvfun_w/py_env-python3.6/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "openshift/configMap-template.yaml", line 22, column 7
found duplicate key "annotations" with value "{}" (original value: "{}")
  in "openshift/configMap-template.yaml", line 27, column 7

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

kebechet/exception.py:40: error: Too many arguments for "__init__" of "BaseException"
kebechet/payload_parser.py:75: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
kebechet/payload_parser.py:76: error: Incompatible types in assignment (expression has type "Dict[str, Optional[Any]]", variable has type "None")
kebechet/payload_parser.py:82: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
kebechet/services.py:49: error: "Callable[[str], Any]" has no attribute "__func__"
kebechet/services.py:56: error: "Callable[[str], Any]" has no attribute "__func__"
kebechet/managers/manager.py:91: error: Incompatible return value type (got "Collection[str]", expected "str")
kebechet/managers/update/update.py:282: error: "Set[Any]" has no attribute "get_all_commits"
kebechet/managers/update/update.py:288: error: "Set[Any]" has no attribute "id"
kebechet/managers/update/update.py:362: error: Argument 4 to "_open_merge_request_update" of "UpdateManager" has incompatible type "Optional[List[Any]]"; expected "List[Any]"
kebechet/managers/update/update.py:364: error: Item "int" of "Optional[int]" has no attribute "id"
kebechet/managers/update/update.py:364: error: Item "None" of "Optional[int]" has no attribute "id"
kebechet/managers/update/update.py:371: error: Argument 4 to "_open_merge_request_update" of "UpdateManager" has incompatible type "Optional[List[Any]]"; expected "List[Any]"
kebechet/managers/update/update.py:373: error: Item "int" of "Optional[int]" has no attribute "id"
kebechet/managers/update/update.py:373: error: Item "None" of "Optional[int]" has no attribute "id"
kebechet/managers/update/update.py:426: error: "Set[Any]" has no attribute "id"
kebechet/managers/update/update.py:429: error: "Set[Any]" has no attribute "get_all_commits"
kebechet/managers/update/update.py:439: error: "Set[Any]" has no attribute "comment"
kebechet/managers/update/update.py:441: error: "Set[Any]" has no attribute "id"
kebechet/managers/update/update.py:456: error: Missing return statement
kebechet/managers/update/update.py:460: error: Return value expected
kebechet/managers/update/update.py:654: error: Return value expected
kebechet/managers/version/version.py:261: error: Signature of "run" incompatible with supertype "ManagerBase"
kebechet/managers/version/version.py:306: error: 'None' object is not iterable
kebechet/managers/version/version.py:306: error: Argument 2 to "_adjust_version_in_sources" of "VersionManager" has incompatible type "Optional[List[Any]]"; expected "List[Any]"
kebechet/managers/pipfile_requirements/pipfile_requirements.py:42: error: Incompatible types in assignment (expression has type "MutableMapping[str, Any]", variable has type "str")
kebechet/managers/pipfile_requirements/pipfile_requirements.py:45: error: "str" has no attribute "items"
kebechet/managers/pipfile_requirements/pipfile_requirements.py:45: error: Invalid index type "str" for "str"; expected type "Union[int, slice]"
kebechet/managers/pipfile_requirements/pipfile_requirements.py:63: error: "str" has no attribute "items"
kebechet/managers/pipfile_requirements/pipfile_requirements.py:75: error: Signature of "run" incompatible with supertype "ManagerBase"
kebechet/managers/thoth_advise/thoth_advise.py:81: error: Return value expected
kebechet/managers/thoth_advise/thoth_advise.py:91: error: Return value expected
kebechet/managers/info/info.py:38: error: Missing return statement
kebechet/managers/info/info.py:38: error: Signature of "run" incompatible with supertype "ManagerBase"
kebechet/managers/info/info.py:43: error: Return value expected
kebechet/managers/info/info.py:47: error: Return value expected
kebechet/managers/version/version_test.py:37: error: Incompatible return value type (got "str", expected "List[str]")
kebechet/config.py:83: error: Incompatible types in assignment (expression has type "Service", variable has type "str")
kebechet/config.py:84: error: "str" has no attribute "download_kebechet_config"
kebechet/config.py:89: error: Incompatible types in assignment (expression has type "PayloadParser", variable has type "Dict[Any, Any]")
kebechet/config.py:90: error: "Dict[Any, Any]" has no attribute "parsed_data"
kebechet/config.py:126: error: Incompatible types in assignment (expression has type "Service", variable has type "str")
kebechet/config.py:127: error: "str" has no attribute "token"
kebechet/config.py:155: error: "str" has no attribute "service"
kebechet/config.py:167: error: The return type of a generator function should be "Generator" or one of its supertypes
kebechet/config.py:219: error: Cannot assign to a method
kebechet/config.py:225: error: Cannot assign to a method
kebechet/config.py:231: error: Cannot assign to a method
kebechet/config.py:237: error: Cannot assign to a method
kebechet/config.py:243: error: Cannot assign to a method
kebechet/config.py:249: error: Cannot assign to a method
kebechet/config.py:278: error: Incompatible types in assignment (expression has type "Service", variable has type "str")
kebechet/config.py:279: error: "str" has no attribute "token"
kebechet/config.py:291: error: Incompatible types in assignment (expression has type "Type[ThothProvenanceManager]", variable has type "Type[ThothAdviseManager]")
kebechet/config.py:306: error: "str" has no attribute "service"
Found 55 errors in 11 files (checked 24 source files)

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /workspace/repo/kebechet/__init__.py
reformatted /workspace/repo/kebechet/managers/__init__.py
reformatted /workspace/repo/kebechet/managers/info/messages.py
reformatted /workspace/repo/kebechet/managers/info/info.py
reformatted /workspace/repo/kebechet/cli.py
reformatted /workspace/repo/kebechet/managers/manager.py
reformatted /workspace/repo/kebechet/managers/pipfile_requirements/pipfile_requirements.py
reformatted /workspace/repo/kebechet/managers/update/messages.py
reformatted /workspace/repo/kebechet/managers/thoth_provenance/thoth_provenance.py
reformatted /workspace/repo/kebechet/managers/thoth_advise/thoth_advise.py
reformatted /workspace/repo/kebechet/managers/version/version_test.py
reformatted /workspace/repo/kebechet/payload_parser.py
reformatted /workspace/repo/kebechet/config.py
reformatted /workspace/repo/kebechet/utils.py
reformatted /workspace/repo/kebechet/services.py
reformatted /workspace/repo/setup.py
reformatted /workspace/repo/kebechet/managers/version/version.py
reformatted /workspace/repo/kebechet/managers/update/update.py
All done! ✨ 🍰 ✨
18 files reformatted, 7 files left unchanged.

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

kebechet/config.py:23:1: F401 'tempfile' imported but unused
kebechet/config.py:84:9: F811 redefinition of unused 'tempfile' from line 23
kebechet/config.py:107:9: F811 redefinition of unused 'tempfile' from line 23
kebechet/config.py:164:13: F841 local variable 'exc' is assigned to but never used
kebechet/config.py:264:9: F811 redefinition of unused 'tempfile' from line 23
kebechet/config.py:387:17: F841 local variable 'exc' is assigned to but never used
kebechet/managers/thoth_advise/thoth_advise.py:27:1: F401 'git' imported but unused
kebechet/managers/thoth_advise/thoth_advise.py:29:1: F401 'kebechet.exception.DependencyManagementError' imported but unused
kebechet/managers/thoth_advise/thoth_advise.py:30:1: F401 'kebechet.exception.InternalError' imported but unused
kebechet/managers/thoth_advise/thoth_advise.py:31:1: F401 'kebechet.exception.PipenvError' imported but unused
kebechet/managers/thoth_advise/thoth_advise.py:33:1: F401 'thoth.sourcemanagement.sourcemanagement.Issue' imported but unused
kebechet/managers/thoth_advise/thoth_advise.py:34:1: F401 'thoth.sourcemanagement.sourcemanagement.PullRequest' imported but unused
kebechet/managers/thoth_advise/thoth_advise.py:164:17: F841 local variable 'branch' is assigned to but never used
kebechet/managers/thoth_provenance/thoth_provenance.py:23:1: F401 'json' imported but unused
kebechet/managers/thoth_provenance/thoth_provenance.py:24:1: F401 'typing' imported but unused
kebechet/managers/thoth_provenance/thoth_provenance.py:28:1: F401 'git' imported but unused
kebechet/managers/thoth_provenance/thoth_provenance.py:30:1: F401 'kebechet.exception.DependencyManagementError' imported but unused
kebechet/managers/thoth_provenance/thoth_provenance.py:31:1: F401 'kebechet.exception.InternalError' imported but unused
kebechet/managers/thoth_provenance/thoth_provenance.py:32:1: F401 'kebechet.exception.PipenvError' imported but unused
kebechet/managers/thoth_provenance/thoth_provenance.py:34:1: F401 'thoth.sourcemanagement.sourcemanagement.Issue' imported but unused
kebechet/managers/thoth_provenance/thoth_provenance.py:35:1: F401 'thoth.sourcemanagement.sourcemanagement.PullRequest' imported but unused
kebechet/managers/thoth_provenance/__init__.py:20:1: F401 '.thoth_provenance.ThothProvenanceManager' imported but unused
kebechet/managers/update/__init__.py:3:1: F401 '.update.UpdateManager' imported but unused
kebechet/managers/pipfile_requirements/__init__.py:3:1: F401 '.pipfile_requirements.PipfileRequirementsManager' imported but unused
kebechet/managers/update/update.py:670:23: F821 undefined name 'exc'
kebechet/managers/update/update.py:702:27: F821 undefined name 'exc'
kebechet/managers/thoth_advise/__init__.py:20:1: F401 '.thoth_advise.ThothAdviseManager' imported but unused
kebechet/managers/version/version_test.py:8:1: F401 'git.Repo' imported but unused
kebechet/payload_parser.py:20:1: F401 'thoth.sourcemanagement.enums.ServiceType' imported but unused
kebechet/managers/version/__init__.py:3:1: F401 '.version.VersionManager' imported but unused
kebechet/managers/info/__init__.py:3:1: F401 '.info.InfoManager' imported but unused
kebechet/__init__.py:3:1: F401 'thoth.sourcemanagement.enums.ServiceType' imported but unused
kebechet/__init__.py:4:1: F401 '.managers.InfoManager' imported but unused
kebechet/__init__.py:5:1: F401 '.managers.UpdateManager' imported but unused

check-manifest...........................................................Failed
- hook id: check-manifest
- exit code: 1

lists of files in version control and sdist do not match!
missing from sdist:
  .coafile
  .pre-commit-config.yaml
  .thoth.yaml
  .zuul.yaml
  CHANGELOG.md
  Dockerfile
  OWNERS
  Pipfile
  Pipfile.lock
  app.sh
  config
  config/aicoe.yaml
  config/thoth.yaml
  kebechet-cli
  kebechet/managers/README.rst
  kebechet/managers/info/README.rst
  kebechet/managers/pipfile_requirements/README.rst
  kebechet/managers/thoth_advise/README.rst
  kebechet/managers/thoth_provenance/README.rst
  kebechet/managers/update/README.rst
  kebechet/managers/version/README.rst
  openshift
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-kebechet-template.yaml
  openshift/kebechet-template.yaml
  openshift/secret-template.yaml
  playbooks
  playbooks/deprovision.yaml
  playbooks/provision.yaml
  playbooks/roles
  playbooks/roles/thoth-kebechet-bot
  playbooks/roles/thoth-kebechet-bot/tasks
  playbooks/roles/thoth-kebechet-bot/tasks/main.yaml
  playbooks/roles/thoth-kebechet-imagestreams
  playbooks/roles/thoth-kebechet-imagestreams/tasks
  playbooks/roles/thoth-kebechet-imagestreams/tasks/main.yaml
  playbooks/roles/thoth-ssh-key-check
  playbooks/roles/thoth-ssh-key-check/tasks
  playbooks/roles/thoth-ssh-key-check/tasks/main.yaml
  requirements.txt
  workflows
  workflows/templates
  workflows/templates/kebechet-job.yaml
no MANIFEST.in found; you can run 'check-manifest -c' to create one
suggested MANIFEST.in rules:
  include *.lock
  include *.md
  include *.sh
  include *.txt
  include *.yaml
  include Dockerfile
  include OWNERS
  include Pipfile
  recursive-include config *.yaml
  recursive-include kebechet *.rst
  recursive-include openshift *.yaml
  recursive-include playbooks *.yaml
  recursive-include workflows *.yaml
````

**Comment by saisankargochhayat** [comment]
Closed with #470 and #464
