### ISSUE TITLE
ImportError: cannot import name 'generate_log'

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#497]
**Describe the bug**

The latest kebechet fails with the following error code:

```
Traceback (most recent call last):
  File "kebechet-cli", line 27, in <module>
    from kebechet.exception import WebhookPayloadError
  File "/home/user/kebechet/__init__.py", line 4, in <module>
    from .managers import InfoManager  # noqa F401
  File "/home/user/kebechet/managers/__init__.py", line 5, in <module>
    from .version import VersionManager  # noqa F401
  File "/home/user/kebechet/managers/version/__init__.py", line 3, in <module>
    from .version import VersionManager  # noqa F401
  File "/home/user/kebechet/managers/version/version.py", line 34, in <module>
    from thoth.glyph import generate_log
ImportError: cannot import name 'generate_log'
```

**To Reproduce**
1. Check runs of kebechet v0.6.1 in stage environment
2. See error

**Expected behavior**

Kebechet should run successfully.

**Comment by fridex** [comment]
We are somehow still running template project of thoth-glyph:

https://github.com/thoth-station/kebechet/blob/b3f3429ee791549285c1be632f8b00c8b5ed5570/Pipfile.lock#L732-L737
