### ISSUE TITLE
(5) Handling Authentication in Kebechet

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#585]
As a Thoth Developer, 
We should enable Kebechet as a Github app and ask for permissions required in the installation process.
And then get temporary tokens to be used in source-management so that Kebechet can act on repositories that don't have @sesheta as a collaborator.

Things to be done - 
- [x] Add authentication logic to SourceManagement to fetch `PEM_KEY` and `APP_ID` when installation id is provided instead of OAuth token. 
- [x] Add logic to fetch, JWT token from above three values, and then use that to initialize OGR. 
- [x] Add a decorator to refresh tokens it time is beyond expire time and add to every method in source-management. 
- [x] Add Kebechet to pass on installation id to source-management to start app authentication. 
- [x] Change Kebechet to include `PEM_KEY`, `APP_ID` and `INSTALLATION_ID` to be part of env variables in workflow image in thoth-application. 
- [x] Add logic to change GitPython remote URL to get access with APP token, instead of SSH key.

cc @fridex

**Comment by saisankargochhayat** [comment]
Sample issue using app authentication - https://github.com/thoth-station/srcops-testing/issues/253

**Comment by saisankargochhayat** [comment]
Issues seem to be working fine - https://github.com/saisankargochhayat/kebechet_sample/issues/122
However for git push in update manager - 
```
kebechet-run-url-d825430d-733069334: 2020-11-12 23:42:28,532   1 INFO     kebechet.managers.update.update:799: Creating update of dependency thamos in repo saisankargochhayat/kebechet_sample (devel: False)
kebechet-run-url-d825430d-733069334: 2020-11-12 23:42:28,533   1 DEBUG    kebechet.managers.manager:123: Running pipenv command 'pipenv install thamos==1.3.1 --keep-outdated'
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:07,682   1 DEBUG    kebechet.managers.manager:123: Running pipenv command 'pipenv lock --keep-outdated'
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:29,961   1 ERROR    kebechet.managers.update.update:816: Failed to create update for dependency thamos: Cmd('git') failed due to: exit code(128)
kebechet-run-url-d825430d-733069334:   cmdline: git push --force --porcelain origin kebechet-thamos-1.3.1
kebechet-run-url-d825430d-733069334:   stderr: 'fatal: Could not read from remote repository.
kebechet-run-url-d825430d-733069334: 
kebechet-run-url-d825430d-733069334: Please make sure you have the correct access rights
kebechet-run-url-d825430d-733069334: and the repository exists.'
kebechet-run-url-d825430d-733069334: Traceback (most recent call last):
kebechet-run-url-d825430d-733069334:   File "/home/user/kebechet/managers/update/update.py", line 810, in _do_update
kebechet-run-url-d825430d-733069334:     req_dev=req_dev,
kebechet-run-url-d825430d-733069334:   File "/home/user/kebechet/managers/update/update.py", line 449, in _create_update
kebechet-run-url-d825430d-733069334:     merge_request,
kebechet-run-url-d825430d-733069334:   File "/home/user/kebechet/managers/update/update.py", line 301, in _open_merge_request_update
kebechet-run-url-d825430d-733069334:     self._git_push(":pushpin: " + commit_msg, branch_name, files, force_push=True)
kebechet-run-url-d825430d-733069334:   File "/home/user/kebechet/managers/update/update.py", line 376, in _git_push
kebechet-run-url-d825430d-733069334:     self.repo.remote().push(branch_name, force=force_push)
kebechet-run-url-d825430d-733069334:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/git/remote.py", line 849, in push
kebechet-run-url-d825430d-733069334:     return self._get_push_info(proc, progress)
kebechet-run-url-d825430d-733069334:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/git/remote.py", line 736, in _get_push_info
kebechet-run-url-d825430d-733069334:     proc.wait(stderr=stderr_text)
kebechet-run-url-d825430d-733069334:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/git/cmd.py", line 408, in wait
kebechet-run-url-d825430d-733069334:     raise GitCommandError(self.args, status, errstr)
kebechet-run-url-d825430d-733069334: git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
kebechet-run-url-d825430d-733069334:   cmdline: git push --force --porcelain origin kebechet-thamos-1.3.1
kebechet-run-url-d825430d-733069334:   stderr: 'fatal: Could not read from remote repository.
kebechet-run-url-d825430d-733069334: 
kebechet-run-url-d825430d-733069334: Please make sure you have the correct access rights
kebechet-run-url-d825430d-733069334: and the repository exists.'
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:30,443   1 DEBUG    kebechet.managers.update.update:667: Deleting old branch kebechet-thamos-0.10.2
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:31,052   1 DEBUG    kebechet.managers.update.update:667: Deleting old branch kebechet-pytest-5.4.3
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:31,656   1 DEBUG    kebechet.managers.update.update:667: Deleting old branch kebechet-pytest-cov-2.9.0
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:32,263   1 DEBUG    kebechet.managers.update.update:667: Deleting old branch kebechet-pyyaml-5.3.1
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:32,850   1 DEBUG    kebechet.managers.update.update:667: Deleting old branch kebechet-semver-2.10.1
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:33,478   1 DEBUG    kebechet.managers.update.update:667: Deleting old branch kebechet-thoth-common-0.13.9
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:34,175   1 DEBUG    kebechet.managers.update.update:667: Deleting old branch kebechet-toml-0.10.1
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:35,607   1 INFO     kebechet.config:156: Running manager 'info' for 'saisankargochhayat/kebechet_sample'
kebechet-run-url-d825430d-733069334: 2020-11-12 23:44:36,333   1 INFO     kebechet.managers.info.info:49: No issue to report to, exiting
```

**Comment by saisankargochhayat** [comment]
So because sesheta doesn't have access to the repository, we can't push a new branch into the user's repo. Maybe GitPython that we use to interact with repositories needs to use the access token generated by the app to push into a new branch..

**Comment by saisankargochhayat** [comment]
While fetching the the repository using Gitpython should work - 
`repo_url = f'https://{app_name}:{access_token}@{service_url}/{slug}'`

**Comment by saisankargochhayat** [comment]
I will close this issue after testing on the cluster.

**Comment by saisankargochhayat** [comment]
Tested and working on stage.
