### ISSUE TITLE
AttributeError: 'UpdateManager' object has no attribute 'get_access_token'

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#632]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
```
 fmurdaca@pc-7  ~/work/aicoe/jupyterlab-requirements   master ●  argo logs -f kebechet-job-5d57e63b
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:41.86423956Z 2020-12-03 13:19:41,863   1 INFO     thoth.common:323: Setting up logging to a Sentry instance 'sentry.io/1297367', environment 'ocp4-stage' and integrations []
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:41.929301725Z 2020-12-03 13:19:41,928   1 INFO     thoth.common:366: Logging to rsyslog endpoint is turned off
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:41.930328969Z 2020-12-03 13:19:41,930   1 INFO     kebechet:67: Kebechet version: '1.1.4'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:41.93037545Z 2020-12-03 13:19:41,930   1 DEBUG    kebechet:71: Debug mode turned on
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:41.930889567Z 2020-12-03 13:19:41,930   1 INFO     kebechet.services:65: github service detected
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:41.9309858Z 2020-12-03 13:19:41,930   1 INFO     kebechet.services:96: Downloading from https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/.thoth.yaml
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:43.366562313Z 2020-12-03 13:19:43,366   1 INFO     kebechet.services:101: b'host: khemenu.thoth-station.ninja\ntls_verify: false\nrequirements_format: pipenv\n\nruntime_environments:\n  - name: \'rhel:8\'\n    operating_system:\n      name: rhel\n      version: "8.0"\n    python_version: "3.8"\n    recommendation_type: latest\n\nmanagers:\n  - name: update\n    configuration:\n      labels: [bot]\n  - name: info\n  - name: version\n    configuration:\n      maintainers:\n        - pacospace\n        - sesheta\n        - goern\n        - fridex\n      assignees:\n        - sesheta\n      labels: [bot]\n      changelog_file: true\n'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:43.366828888Z 2020-12-03 13:19:43,366   1 DEBUG    kebechet.config:105: Filename = /tmp/tmp5ng19xix
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:43.366960539Z 2020-12-03 13:19:43,366   1 INFO     kebechet.services:65: github service detected
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:43.367115419Z 2020-12-03 13:19:43,367   1 INFO     kebechet.services:96: Downloading from https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/.thoth.yaml
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:44.440053634Z 2020-12-03 13:19:44,439   1 INFO     kebechet.services:101: b'host: khemenu.thoth-station.ninja\ntls_verify: false\nrequirements_format: pipenv\n\nruntime_environments:\n  - name: \'rhel:8\'\n    operating_system:\n      name: rhel\n      version: "8.0"\n    python_version: "3.8"\n    recommendation_type: latest\n\nmanagers:\n  - name: update\n    configuration:\n      labels: [bot]\n  - name: info\n  - name: version\n    configuration:\n      maintainers:\n        - pacospace\n        - sesheta\n        - goern\n        - fridex\n      assignees:\n        - sesheta\n      labels: [bot]\n      changelog_file: true\n'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:44.445193886Z 2020-12-03 13:19:44,444   1 INFO     kebechet.services:65: github service detected
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:44.445422773Z 2020-12-03 13:19:44,445   1 DEBUG    kebechet.config:136: Using token '7b5''*************************************'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:44.445491123Z 2020-12-03 13:19:44,445   1 INFO     kebechet.config:156: Running manager 'update' for 'thoth-station/graph-sync-job'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:44.445564212Z 2020-12-03 13:19:44,445   1 WARNING  kebechet.config:160: Ignoring option {'configuration': {'labels': ['bot']}} in manager entry for 'thoth-station/graph-sync-job'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:44.799125078Z 2020-12-03 13:19:44,798   1 INFO     kebechet.utils:70: Cloning repository https://khebhut:v1.d9aa44bf329f5224e6512940444cfb306037db5b@github.com/thoth-station/graph-sync-job to /tmp/tmp795j9fsf
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:45.210690958Z 2020-12-03 13:19:45,210   1 INFO     kebechet.managers.update.update:809: Using Pipfile for dependency management
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:46.691032271Z 2020-12-03 13:19:46,690   1 INFO     kebechet.managers.update.update:535: Updating all dependencies to their latest version
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:19:46.691417975Z 2020-12-03 13:19:46,691   1 DEBUG    kebechet.managers.manager:146: Running pipenv command 'pipenv update --dev'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:30:30.170377766Z 2020-12-03 13:30:30,167   1 DEBUG    kebechet.managers.manager:146: Running pipenv command 'pipenv lock'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.42871791Z 2020-12-03 13:34:08,426   1 DEBUG    kebechet.managers.update.update:388: Found new update for thoth-storages: 0.29.1 -> 0.29.2 (dev: False)
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.42871791Z 2020-12-03 13:34:08,428   1 INFO     kebechet.managers.update.update:747: Outdated: {'thoth-storages': {'dev': False, 'old_version': '0.29.1', 'new_version': '0.29.2'}}
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.526926137Z 2020-12-03 13:34:08,526   1 DEBUG    kebechet.managers.update.update:330: No pull request was found for automatic update.
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z AttributeError: 'UpdateManager' object has no attribute 'get_access_token'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z 2020-12-03 13:34:08,527   1 ERROR    kebechet.managers.update.update:775: Failed to create update for current master 3eec45c024cb92fea2e5e3b6493673cde0508f0c: 'UpdateManager' object has no attribute 'get_access_token'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z Traceback (most recent call last):
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z   File "/home/user/kebechet/managers/update/update.py", line 769, in _do_update
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z   File "/home/user/kebechet/managers/update/update.py", line 426, in _create_update
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z     body, labels, ["Pipfile.lock"], merge_request
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z   File "/home/user/kebechet/managers/update/update.py", line 303, in _open_merge_request_update
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z     self._git_push(":arrow_up: " + commit_msg, branch_name, files, force_push=True)
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z   File "/home/user/kebechet/managers/manager.py", line 60, in wrapper
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z     req_dev=req_dev,
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:08.529667827Z     manager.token, manager.token_expire_time = manager.get_access_token()
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:17.956692788Z 2020-12-03 13:34:17,956   1 INFO     kebechet.config:156: Running manager 'info' for 'thoth-station/graph-sync-job'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:18.706159414Z 2020-12-03 13:34:18,705   1 INFO     kebechet.managers.info.info:52: Found issue Kebechet info, generating report
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:18.707036832Z 2020-12-03 13:34:18,706   1 INFO     kebechet.utils:70: Cloning repository https://khebhut:v1.23c6c93564090ee675bef52e80a6884137510e5f@github.com/thoth-station/graph-sync-job to /tmp/tmp8c5di511
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:19.541388897Z 2020-12-03 13:34:19,540   1 DEBUG    kebechet.managers.manager:146: Running pipenv command 'pipenv --version'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:34:20.82118707Z 2020-12-03 13:34:20,820   1 DEBUG    kebechet.managers.manager:146: Running pipenv command 'pipenv install --dev --skip-lock'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:35:56.593276596Z 2020-12-03 13:35:56,591   1 DEBUG    kebechet.managers.manager:146: Running pipenv command 'pipenv graph'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:36:07.828124145Z 2020-12-03 13:36:07,826   1 INFO     kebechet.config:156: Running manager 'version' for 'thoth-station/graph-sync-job'
kebechet-job-5d57e63b-2431254001: 2020-12-03T13:36:07.828236182Z 2020-12-03 13:36:07,827   1 WARNING  kebechet.config:160: Ignoring option {'configuration': {'maintainers': ['pacospace', 'sesheta', 'goern', 'fridex'], 'assignees': ['sesheta'], 'labels': ['bot'], 'changelog_file': True}} in manager entry for 'thoth-station/graph-sync-job'

```

**Additional context**

**Comment by pacospace** [comment]
@saisankargochhayat can we close it? :)

**Comment by saisankargochhayat** [comment]
Sure, I was going to try on the cluster and then close :D But we can and reopen if it occurs again.

**Comment by pacospace** [comment]
> Sure, I was going to try on the cluster and then close :D But we can and reopen if it occurs again.

The problem is the workflow won't fail, but succeed in any case. I randomly spotted it, because I was checking why kebechet was not able to update to latest version a packages in graph-sync-job

**Comment by saisankargochhayat** [comment]
> > Sure, I was going to try on the cluster and then close :D But we can and reopen if it occurs again.
> 
> The problem is the workflow won't fail, but succeed in any case. I randomly spotted it, because I was checking why kebechet was not able to update to latest version a packages in graph-sync-job (I ended up doing it unfortunately :/)

Okay, once its released I am going to run on it on graph-sync-job and see the logs to check this doesn't come up :)

**Comment by pacospace** [comment]
> > > Sure, I was going to try on the cluster and then close :D But we can and reopen if it occurs again.
> > 
> > 
> > The problem is the workflow won't fail, but succeed in any case. I randomly spotted it, because I was checking why kebechet was not able to update to latest version a packages in graph-sync-job (I ended up doing it unfortunately :/)
> 
> Okay, once its released I am going to run on it on graph-sync-job and see the logs to check this doesn't come up :)

Thanks a lot @saisankargochhayat :1st_place_medal:
