### ISSUE TITLE
Error in version 1.2.1

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#644]
```
kebechet-job-75f125e6-3483353953: Traceback (most recent call last):
kebechet-job-75f125e6-3483353953:   File "kebechet-cli", line 27, in <module>
kebechet-job-75f125e6-3483353953:     from kebechet.exception import WebhookPayloadError
kebechet-job-75f125e6-3483353953:   File "/home/user/kebechet/__init__.py", line 4, in <module>
kebechet-job-75f125e6-3483353953:     from .managers import InfoManager  # noqa F401
kebechet-job-75f125e6-3483353953:   File "/home/user/kebechet/managers/__init__.py", line 7, in <module>
kebechet-job-75f125e6-3483353953:     from .thoth_advise import ThothAdviseManager
kebechet-job-75f125e6-3483353953:   File "/home/user/kebechet/managers/thoth_advise/__init__.py", line 20, in <module>
kebechet-job-75f125e6-3483353953:     from .thoth_advise import ThothAdviseManager  # noqa F401
kebechet-job-75f125e6-3483353953:   File "/home/user/kebechet/managers/thoth_advise/thoth_advise.py", line 25, in <module>
kebechet-job-75f125e6-3483353953:     from thamos import lib
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/thamos/lib.py", line 40, in <module>
kebechet-job-75f125e6-3483353953:     from thoth.python import Project
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/thoth/python/__init__.py", line 29, in <module>
kebechet-job-75f125e6-3483353953:     from .aiosource import AIOSource, AsyncIterablePackages, AsyncIterableVersions, AsyncIterableArtifacts
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/thoth/python/aiosource.py", line 29, in <module>
kebechet-job-75f125e6-3483353953:     import aiohttp
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib64/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
kebechet-job-75f125e6-3483353953:     from .client import (
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib64/python3.8/site-packages/aiohttp/client.py", line 35, in <module>
kebechet-job-75f125e6-3483353953:     from . import hdrs, http, payload
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib64/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
kebechet-job-75f125e6-3483353953:     from .http_parser import (
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib64/python3.8/site-packages/aiohttp/http_parser.py", line 15, in <module>
kebechet-job-75f125e6-3483353953:     from .helpers import NO_EXTENSIONS, BaseTimerContext
kebechet-job-75f125e6-3483353953:   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib64/python3.8/site-packages/aiohttp/helpers.py", line 48, in <module>
kebechet-job-75f125e6-3483353953:     from typing_extensions import Protocol
kebechet-job-75f125e6-3483353953: ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by goern** [comment]
https://github.com/thoth-station/kebechet/pull/645
