### ISSUE TITLE
kebechet cannot update dependencies due to stderr: 'fatal: remote origin already exists.'

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#664]
**Describe the bug**
kebechet cannot update dependencies due to error `stderr: 'fatal: remote origin already exists.'`

**To Reproduce**
1. Open issue in `Kebechet update` in thoth-station/report-processing

**Expected behavior**
Dependencies are updated sucessfully.

**Screenshots**
```
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.545063318Z 2021-01-11 08:48:13,544   1 INFO     thoth.common:319: Setting up logging to a Sentry instance 'sentry.io/1297367', environment 'ocp4-stage' and integrations ['AioHttpIntegration']
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.57648955Z 2021-01-11 08:48:13,576   1 INFO     thoth.common:366: Logging to rsyslog endpoint is turned off
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.578150873Z 2021-01-11 08:48:13,577   1 INFO     kebechet:67: Kebechet version: '1.2.2'
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.579120782Z 2021-01-11 08:48:13,578   1 DEBUG    kebechet:71: Debug mode turned on
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.579915613Z 2021-01-11 08:48:13,579   1 INFO     kebechet.services:65: github service detected
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.580172722Z 2021-01-11 08:48:13,580   1 INFO     kebechet.services:96: Downloading from https://raw.githubusercontent.com/thoth-station/report-processing/master/.thoth.yaml
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.756854383Z 2021-01-11 08:48:13,756   1 INFO     kebechet.services:101: b'host: khemenu.thoth-station.ninja\ntls_verify: true\nrequirements_format: pipenv\n\nruntime_environments:\n  - name: ubi8\n    operating_system:\n      name: ubi\n      version: "8"\n    python_version: "3.6"\n    recommendation_type: latest\n\nmanagers:\n  - name: update\n    configuration:\n      labels: [bot]\n  - name: info\n  - name: version\n    configuration:\n      maintainers:\n        - fridex\n        - goern\n        - harshad16\n        - pacospace\n        - sesheta\n      assignees:\n        - sesheta\n      labels: [bot]\n      changelog_file: true\n'
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.75706814Z 2021-01-11 08:48:13,756   1 DEBUG    kebechet.config:105: Filename = /tmp/tmp35y1giiv
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.757137141Z 2021-01-11 08:48:13,757   1 INFO     kebechet.services:65: github service detected
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.75726477Z 2021-01-11 08:48:13,757   1 INFO     kebechet.services:96: Downloading from https://raw.githubusercontent.com/thoth-station/report-processing/master/.thoth.yaml
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.830222751Z 2021-01-11 08:48:13,829   1 INFO     kebechet.services:101: b'host: khemenu.thoth-station.ninja\ntls_verify: true\nrequirements_format: pipenv\n\nruntime_environments:\n  - name: ubi8\n    operating_system:\n      name: ubi\n      version: "8"\n    python_version: "3.6"\n    recommendation_type: latest\n\nmanagers:\n  - name: update\n    configuration:\n      labels: [bot]\n  - name: info\n  - name: version\n    configuration:\n      maintainers:\n        - fridex\n        - goern\n        - harshad16\n        - pacospace\n        - sesheta\n      assignees:\n        - sesheta\n      labels: [bot]\n      changelog_file: true\n'
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.838554865Z 2021-01-11 08:48:13,838   1 INFO     kebechet.services:65: github service detected
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.838790112Z 2021-01-11 08:48:13,838   1 DEBUG    kebechet.config:136: Using token '7b5''*************************************'
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.838824641Z 2021-01-11 08:48:13,838   1 INFO     kebechet.config:156: Running manager 'update' for 'thoth-station/report-processing'
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:13.8389759Z 2021-01-11 08:48:13,838   1 WARNING  kebechet.config:159: Ignoring option {'configuration': {'labels': ['bot']}} in manager entry for 'thoth-station/report-processing'
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:14.187854275Z 2021-01-11 08:48:14,187   1 INFO     kebechet.utils:70: Cloning repository https://khebhut:v1.4e1ff4f0bc31fcb6aa4a5271e1f2315ee2937da0@github.com/thoth-station/report-processing to /tmp/tmplr19xyzz
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:14.672008377Z 2021-01-11 08:48:14,671   1 INFO     kebechet.managers.update.update:808: Using Pipfile for dependency management
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:16.508530401Z 2021-01-11 08:48:16,508   1 INFO     kebechet.managers.update.update:534: Updating all dependencies to their latest version
kebechet-job-c04b432e-50054755: 2021-01-11T08:48:16.508757815Z 2021-01-11 08:48:16,508   1 DEBUG    kebechet.managers.manager:146: Running pipenv command 'pipenv update --dev'
kebechet-job-c04b432e-50054755: 2021-01-11T08:56:19.818758927Z 2021-01-11 08:56:19,818   1 DEBUG    kebechet.managers.manager:146: Running pipenv command 'pipenv lock'
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.522422626Z 2021-01-11 08:59:11,521   1 DEBUG    kebechet.managers.update.update:386: Found new update for thoth-storages: 0.29.4 -> 0.30.1 (dev: False)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.522516542Z 2021-01-11 08:59:11,522   1 DEBUG    kebechet.managers.update.update:386: Found new update for scikit-learn: 0.23.2 -> 0.24.0 (dev: False)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.522532327Z 2021-01-11 08:59:11,522   1 DEBUG    kebechet.managers.update.update:386: Found new update for numpy: 1.19.4 -> 1.19.5 (dev: False)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.522833747Z 2021-01-11 08:59:11,522   1 DEBUG    kebechet.managers.update.update:386: Found new update for deepdiff: 5.0.2 -> 5.2.1 (dev: False)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.522944695Z 2021-01-11 08:59:11,522   1 DEBUG    kebechet.managers.update.update:386: Found new update for pytest: 6.1.2 -> 6.2.1 (dev: True)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.523152559Z 2021-01-11 08:59:11,522   1 INFO     kebechet.managers.update.update:746: Outdated: {'thoth-storages': {'dev': False, 'old_version': '0.29.4', 'new_version': '0.30.1'}, 'scikit-learn': {'dev': False, 'old_version': '0.23.2', 'new_version': '0.24.0'}, 'numpy': {'dev': False, 'old_version': '1.19.4', 'new_version': '1.19.5'}, 'deepdiff': {'dev': False, 'old_version': '5.0.2', 'new_version': '5.2.1'}, 'pytest': {'dev': True, 'old_version': '6.1.2', 'new_version': '6.2.1'}}
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.700317338Z 2021-01-11 08:59:11,699   1 DEBUG    kebechet.managers.update.update:329: No pull request was found for automatic update.
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     self._git_push(":arrow_up: " + commit_msg, branch_name, files, force_push=True)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   cmdline: git remote add origin https://khebhut:v1.86e94e2ee06bbe52dd2bbdd497cc00a78853cf78@github.com/thoth-station/report-processing
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   stderr: 'fatal: remote origin already exists.'
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z Traceback (most recent call last):
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/kebechet/managers/update/update.py", line 762, in _do_update
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     versions = self._create_update(
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/kebechet/managers/update/update.py", line 424, in _create_update
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     merge_request = self._open_merge_request_update(
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/kebechet/managers/update/update.py", line 302, in _open_merge_request_update
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z 2021-01-11 08:59:11,722   1 ERROR    kebechet.managers.update.update:773: Failed to create update for current master 7cad3661eb629f4ad5b66c5e47f1368a2cc5ac65: Cmd('git') failed due to: exit code(128)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/kebechet/managers/manager.py", line 62, in wrapper
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     manager._repo.create_remote(
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/repo/base.py", line 412, in create_remote
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     return Remote.create(self, name, url, **kwargs)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/remote.py", line 613, in create
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     repo.git.remote(scmd, name, Git.polish_url(url), **kwargs)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     return self.execute(call, **exec_kwargs)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z     raise GitCommandError(command, status, stderr_value, stdout_value)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   cmdline: git remote add origin https://khebhut:v1.86e94e2ee06bbe52dd2bbdd497cc00a78853cf78@github.com/thoth-station/report-processing
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:11.725848847Z   stderr: 'fatal: remote origin already exists.'
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:14.805035951Z 2021-01-11 08:59:14,804   1 INFO     kebechet.config:156: Running manager 'info' for 'thoth-station/report-processing'
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:20.72814421Z 2021-01-11 08:59:20,727   1 INFO     kebechet.managers.info.info:49: No issue to report to, exiting
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:20.728533557Z 2021-01-11 08:59:20,728   1 INFO     kebechet.config:156: Running manager 'version' for 'thoth-station/report-processing'
kebechet-job-c04b432e-50054755: 2021-01-11T08:59:20.728533557Z 2021-01-11 08:59:20,728   1 WARNING  kebechet.config:159: Ignoring option {'configuration': {'maintainers': ['fridex', 'goern', 'harshad16', 'pacospace', 'sesheta'], 'assignees': ['sesheta'], 'labels': ['bot'], 'changelog_file': True}} in manager entry for 'thoth-station/report-processing'

```

**Additional context**

**Comment by fridex** [comment]
It looks like the branch with updates was note deleted from the remote. Created https://github.com/thoth-station/report-processing/issues/90

**Comment by pacospace** [comment]
> It looks like the branch with updates was note deleted from the remote. Created [thoth-station/report-processing#90](https://github.com/thoth-station/report-processing/issues/90)

Thanks! It already failed twice :/

**Comment by pacospace** [comment]
> It looks like the branch with updates was note deleted from the remote. Created [thoth-station/report-processing#90](https://github.com/thoth-station/report-processing/issues/90)

It worked this time: https://github.com/thoth-station/report-processing/pull/91. Not sure why it failed twice before :/
