### ISSUE TITLE
Failed to retrieve version information for dependency pandas_profiling

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#710]
**Describe the bug**

kebechet was not able to update the pipfile.lock due to the pandas_profiling 

```
2021-04-01 18:20:38,637   1 ERROR    kebechet.config:168: An error occurred during run of manager {'configuration': {'labels': ['bot']}} <class 'kebechet.managers.update.update.UpdateManager'> for 'aicoe-aiops/ocp-ci-analysis', skipping
Traceback (most recent call last):
  File "/home/user/kebechet/config.py", line 166, in run_url
    instance.run(**manager_configuration)
  File "/home/user/kebechet/managers/update/update.py", line 813, in run
    result = self._do_update(labels, pipenv_used=True, req_dev=False)
  File "/home/user/kebechet/managers/update/update.py", line 702, in _do_update
    old_direct_dependencies_version = self._get_direct_dependencies_version()
  File "/home/user/kebechet/managers/update/update.py", line 249, in _get_direct_dependencies_version
    version = cls._get_dependency_version(dependency, is_dev=is_dev)
  File "/home/user/kebechet/managers/update/update.py", line 127, in _get_dependency_version
    raise InternalError(
kebechet.exception.InternalError: Failed to retrieve version information for dependency pandas_profiling, (dev: False)
```

**Additional context**

Related-to:
https://github.com/aicoe-aiops/ocp-ci-analysis/issues/205
https://github.com/aicoe-aiops/ocp-ci-analysis/pull/200

**Comment by goern** [comment]
@harshad16 is this a bug or missing information the the knowledge graph?

/label triage/needs-information

**Comment by harshad16** [comment]
This bug happens due to the name of the package not following canonical form.
for example:  pandas_profiling
instead of using pandas-profiling https://pypi.org/project/pandas-profiling/

**Comment by goern** [comment]
https://github.com/pypa/pipenv/issues/4699
