### ISSUE TITLE
kebechet v1.3.0 causing following error.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#735]
**Describe the bug**
kebechet v1.3.0 has these errors.

```
Traceback (most recent call last):
  File "kebechet-cli", line 28, in <module>
    from kebechet.exception import WebhookPayloadError
  File "/home/user/kebechet/__init__.py", line 3, in <module>
    from .managers import InfoManager  # noqa F401
  File "/home/user/kebechet/managers/__init__.py", line 3, in <module>
    from .info import InfoManager
  File "/home/user/kebechet/managers/info/__init__.py", line 3, in <module>
    from .info import InfoManager  # noqa F401
  File "/home/user/kebechet/managers/info/info.py", line 23, in <module>
    from kebechet.managers.manager import ManagerBase
  File "/home/user/kebechet/managers/manager.py", line 31, in <module>
    from ogr.services.base import BaseGitService
ModuleNotFoundError: No module named 'ogr'
```

**Comment by harshad16** [comment]
this is fixed with version v1.3.2
closing the issue.
