### ISSUE TITLE
kebechet run fails due to non correct branch being passed

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#774]
**Describe the bug**

There is a bug , the branch is not being passed correctly. 
```
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 484, in get_file_content
    return self.github_repo.get_contents(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1789, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kebechet-cli", line 165, in <module>
    cli()
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "kebechet-cli", line 161, in cli_run_webhook
    run_webhook(payload=payload)
  File "/home/user/kebechet/kebechet_runners.py", line 67, in run_webhook
    run_url(url, service_type, parsed_payload)
  File "/home/user/kebechet/kebechet_runners.py", line 88, in run_url
    run(
  File "/home/user/kebechet/kebechet_runners.py", line 142, in run
    with download_kebechet_config(ogr_service, namespace, project) as f:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/kebechet/utils.py", line 117, in download_kebechet_config
    content = ogr_project.get_file_content(".thoth.yaml", ref=branch)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 489, in get_file_content
    raise FileNotFoundError(f"File '{path}' on {ref} not found", ex)
FileNotFoundError: [Errno File '.thoth.yaml' on main not found] 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

```

The branch is not being passed https://github.com/thoth-station/kebechet/blob/bca1ea008cbc0085cc72a6d4c694d0d3c2bbc8fe/kebechet/utils.py#L109
from the function
https://github.com/thoth-station/kebechet/blob/120d2277c68513b751cca78f6e0c180b9fa31739/kebechet/kebechet_runners.py#L142

kebechet version: [v1.4.0](https://github.com/thoth-station/kebechet/tree/refs/tags/v1.4.0)
complete log: http://pastebin.test.redhat.com/983851

**Expected behavior**
smooth run of kebechet

**Comment by KPostOffice** [comment]
Hey, @harshad16 could you let me know which repository this was run on. This utility function should work fine without being passed a branch name as it defaults to the project default.

**Comment by harshad16** [comment]
i had seen this , when opened calend release for thoth-application

**Comment by goern** [comment]
ping
