### ISSUE TITLE
Handle the nonetype catch during kebechet update

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#776]
**Describe the bug**

The kebechet update is getting failed at a point, it getting nonetype error while executing the kebechet update

```
2021-08-09 07:40:49,143   1 ERROR    kebechet.managers.update.update:835: Failed to create update for current master e80645a37e2353c62cf1168a7a72bd219f1fc8d7: None
Traceback (most recent call last):
  File "/home/user/kebechet/managers/update/update.py", line 823, in _do_update
    versions = self._create_update(
  File "/home/user/kebechet/managers/update/update.py", line 457, in _create_update
    pull_request = self._open_merge_request_update(
  File "/home/user/kebechet/managers/update/update.py", line 331, in _open_merge_request_update
    merge_request = self.project.create_pr(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/read_only.py", line 70, in readonly_func
    return func(self, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/utils.py", line 173, in indirectly_called
    return specialized_function(self, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/pull_request.py", line 177, in create
    created_pr = github_repo.create_pull(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1348, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1364, in __create_pull_1
    assert isinstance(head, str), head
AssertionError: None
```

**Expected behavior**
successfully execution of the update

**Comment by goern** [comment]
/assign @KPostOffice 
/priority important-soon

is this still valid? @harshad16
