### ISSUE TITLE
Kebechet fails when .thoth.yaml is missing

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#797]
**Describe the bug**
Kebechet fails when .thoth.yaml is missing

**To Reproduce**

**Expected behavior**

**Screenshots**
```
2021-08-25 09:29:19,456   1 INFO     thoth.common:319: Setting up logging to a Sentry instance 'sentry.io/1297367', environment 'zero-prod' and integrations ['AioHttpIntegration']
2021-08-25 09:29:19,486   1 INFO     thoth.common:366: Logging to rsyslog endpoint is turned off
2021-08-25 09:29:19,489   1 INFO     kebechet:68: Kebechet version: '1.4.1'
2021-08-25 09:29:19,489   1 DEBUG    kebechet:72: Debug mode turned on
2021-08-25 09:29:20,103   1 CRITICAL root:105: Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 484, in get_file_content
    return self.github_repo.get_contents(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1789, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kebechet-cli", line 165, in <module>
    cli()
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "kebechet-cli", line 161, in cli_run_webhook
    run_webhook(payload=payload)
  File "/home/user/kebechet/kebechet_runners.py", line 71, in run_webhook
    run_url(url, service_type, parsed_payload)
  File "/home/user/kebechet/kebechet_runners.py", line 92, in run_url
    run(
  File "/home/user/kebechet/kebechet_runners.py", line 146, in run
    with download_kebechet_config(ogr_service, namespace, project) as f:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/kebechet/utils.py", line 119, in download_kebechet_config
    content = ogr_project.get_file_content(".thoth.yaml", ref=branch)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 489, in get_file_content
    raise FileNotFoundError(f"File '{path}' on {ref} not found", ex)
FileNotFoundError: [Errno File '.thoth.yaml' on master not found] 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Additional context**

**Comment by KPostOffice** [comment]
Kebechet should fail in this case but we should instead open an issue with why and an example `.thoth.yaml` file

**Comment by fridex** [comment]
> Kebechet should fail in this case but we should instead open an issue with why and an example `.thoth.yaml` file

What about directly opening a pull request with `.thoth.yaml` to be reviewed?

**Comment by pacospace** [comment]
I think this was solved by @KPostOffice already @goern , see: https://github.com/thoth-station/support/pull/21

**Comment by pacospace** [comment]
We can close this, feel free to reopen it!
