### ISSUE TITLE
kebechet run-webhook is failing 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#906]
**Describe the bug**
The kebechet run-webhook is failing 
kebechet version: v1.6.2

```
Traceback (most recent call last):
  File "kebechet-cli", line 28, in <module>
    from kebechet.exception import WebhookPayloadError
  File "/home/user/kebechet/__init__.py", line 3, in <module>
    from .managers import InfoManager  # noqa F401
  File "/home/user/kebechet/managers/__init__.py", line 4, in <module>
    from .info import InfoManager
  File "/home/user/kebechet/managers/info/__init__.py", line 3, in <module>
    from .info import InfoManager  # noqa F401
  File "/home/user/kebechet/managers/info/info.py", line 23, in <module>
    from kebechet.managers.manager import ManagerBase
  File "/home/user/kebechet/managers/manager.py", line 34, in <module>
    from kebechet import utils
  File "/home/user/kebechet/utils.py", line 40, in <module>
    from . import __version__ as keb_version
ImportError: cannot import name '__version__' from partially initialized module 'kebechet' (most likely due to a circular import) (/home/user/kebechet/__init__.py)
```

**Comment by harshad16** [comment]
the init.py import infomanager and updatemanager 
which are inturn import the utils https://github.com/thoth-station/kebechet/blob/69b3375e0dd133a89fd072ead04ca2ff6088a634/kebechet/managers/update/update.py#L40
