### ISSUE TITLE
Kebechet failing with the github.GithubException.GithubException

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#910]
**Describe the bug**

Kebechet failing with the github.GithubException.GithubException and error code 404
Kebechet version: **v1.6.3**

```
2021-11-16 18:28:36,472   1 WARNING  ogr.services.github.pull_request:151: CartoonFan/loot is fork, ignoring fork_repo.
2021-11-16 18:28:36,621   1 CRITICAL root:105: Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 404, in get_file_content
    return self.github_repo.get_contents(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1789, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/kebechet/kebechet_runners.py", line 156, in run
    with download_kebechet_config(ogr_service, namespace, project) as f:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/kebechet/utils.py", line 133, in download_kebechet_config
    content = ogr_project.get_file_content(".thoth.yaml", ref=branch)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/abstract.py", line 63, in wrapper
    return function(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 409, in get_file_content
    raise FileNotFoundError(f"File '{path}' on {ref} not found") from ex
FileNotFoundError: File '.thoth.yaml' on develop not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kebechet-cli", line 165, in <module>
    cli()
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "kebechet-cli", line 161, in cli_run_webhook
    run_webhook(payload=payload)
  File "/home/user/kebechet/kebechet_runners.py", line 78, in run_webhook
    run_url(url, service_type, parsed_payload)
  File "/home/user/kebechet/kebechet_runners.py", line 99, in run_url
    run(
  File "/home/user/kebechet/kebechet_runners.py", line 160, in run
    ConfigInitializer(
  File "/home/user/kebechet/managers/config_initializer/config_initializer.py", line 61, in run
    self.project.create_pr(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/abstract.py", line 63, in wrapper
    return function(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/read_only.py", line 74, in readonly_func
    return func(self, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/utils.py", line 199, in indirectly_called
    return specialized_function(self, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/abstract.py", line 63, in wrapper
    return function(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/pull_request.py", line 161, in create
    created_pr = github_repo.create_pull(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1348, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1379, in __create_pull_1
    return self.__create_pull(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Repository.py", line 1392, in __create_pull
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

**Comment by harshad16** [comment]
This is fixed with the commit : https://github.com/thoth-station/kebechet/commit/9fdc35c8a1c637dcc3d4d5b40eb50fe47b0c7358
and also available from v1.6.4 and above
