### ISSUE TITLE
Key error on configuration entries

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#93]
```python
  | 2018-07-26 09:53:17,124 [1] DEBUG    kebechet: Debug mode turned on
-- | --
  | 2018-07-26 09:53:17,273 [1] DEBUG    kebechet.config: Using token '569*************************************'
  | 2018-07-26 09:53:17,273 [1] INFO     kebechet.config: Running manager 'update' for 'thoth-station/adviser'
  | 2018-07-26 09:53:17,274 [1] INFO     kebechet.utils: Cloning repository git@github.com:thoth-station/adviser.git to /tmp/tmpv9jx0hzn
  | 2018-07-26 09:53:17,720 [1] INFO     kebechet.managers.update.update: Using Pipfile for dependency management
  | 2018-07-26 09:53:18,108 [1] DEBUG    kebechet.source_management: Issue 'No dependency management found' not found, not closing it
  | 2018-07-26 09:53:18,544 [1] DEBUG    kebechet.source_management: Issue 'Failed to perform initial lock of software stack' not found, not closing it
  | 2018-07-26 09:53:18,547 [1] INFO     kebechet.managers.update.update: Updating all dependencies to their latest version
  | 2018-07-26 09:53:18,547 [1] DEBUG    kebechet.managers.manager: Running pipenv command 'pipenv update --dev'
  | 2018-07-26 09:55:58,214 [1] DEBUG    kebechet.managers.manager: Running pipenv command 'pipenv lock'
  | 2018-07-26 09:56:09,472 [1] DEBUG    kebechet.source_management: Issue 'Failed to update dependencies to their latest version' not found, not closing it
  | 2018-07-26 09:56:09,474 [1] INFO     kebechet.managers.update.update: Outdated: {}
  | 2018-07-26 09:56:09,884 [1] DEBUG    kebechet.source_management: Issue 'Failed to replicate environment for updates' not found, not closing it
  | 2018-07-26 09:56:10,655 [1] INFO     kebechet.config: Running manager 'info' for 'thoth-station/adviser'
  | 2018-07-26 09:56:11,226 [1] INFO     kebechet.managers.info.info: No issue to report to, exiting
  | 2018-07-26 09:56:11,226 [1] INFO     kebechet.config: Running manager 'version' for 'thoth-station/adviser'
  | 2018-07-26 09:56:11,226 [1] ERROR    kebechet.config: An error occurred during run of manager {} <class 'kebechet.managers.version.version.VersionManager'> for thoth-station/adviser, skipping
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/site-packages/kebechet/config.py", line 139, in run
  | instance.run(**manager_configuration)
  | TypeError: run() got an unexpected keyword argument 'maintainers'

```

Hint: Most probably this is caused by poping things from config:

```python

2018-07-26 09:56:11,227 [1] ERROR    kebechet.config: No manager name provided in configuration entry for thoth-station/cleanup-job, ignoring entry
--
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/site-packages/kebechet/config.py", line 122, in run
  | manager_name = manager.pop('name')

```

**Comment by fridex** [comment]
Fixed in #94.
