### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#942]
**Describe the bug**
```
Traceback (most recent call last):
  File "update_keb_installation.py", line 142, in <module>
    update_keb_installation()
  File "update_keb_installation.py", line 58, in update_keb_installation
    project = service.get_project(namespace=_SLUG.split("/")[0], repo=_SLUG.split("/")[1])
IndexError: list index out of range
```

**Comment by harshad16** [comment]
Reverted the https://github.com/thoth-station/thoth-application/pull/2191
due to the above issue.

cc: @KPostOffice  @pacospace

**Comment by codificat** [comment]
/transfer workflow-helpers
where the referenced code is

**Comment by codificat** [comment]
Trying again now that the prow plugin is there:
/transfer workflow-helpers
