### ISSUE TITLE
fatal: ambiguous argument unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#981]
**Describe the bug**
This request was opened by one of the user of kebechet.
https://github.com/AICoE/summit-2021-octo-keynote/issues/52
However the kebechet pod failed with the following error:
```
Traceback (most recent call last):
  File "/home/user/kebechet/kebechet_runners.py", line 210, in run
    instance.run(**manager_configuration)
  File "/home/user/kebechet/managers/version/version.py", line 313, in run
    ) = self._branch_and_update_vers_and_changelog(
  File "/home/user/kebechet/managers/version/version.py", line 121, in _branch_and_update_vers_and_changelog
    changelog = utils._compute_changelog(
  File "/home/user/kebechet/managers/version/utils.py", line 159, in _compute_changelog
    changelog = repo.git.log(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/cmd.py", line 638, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/cmd.py", line 1183, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/cmd.py", line 983, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git log --no-merges --format=* %s 0.3.0..HEAD
  stderr: 'fatal: ambiguous argument '0.3.0..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```

**Comment by KPostOffice** [comment]
Issue has to do with "v" being dropped from the beginning of the ref

**Comment by KPostOffice** [comment]
fixed by: https://github.com/thoth-station/kebechet/pull/982
/close
